import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../core/models/business.dart';
import '../../../services/business/business_repository.dart';
import 'business_detail_screen.dart';
import 'saved_businesses_screen.dart';
import '../../messenger/presentation/messenger_screen.dart';
import '../../../services/core/auren_core_five_repository.dart';
import '../../../services/core/auren_core_five_repository.dart';
import '../../../services/core/auren_core_five_repository.dart';
class AurenBusinessScreen extends StatefulWidget{const AurenBusinessScreen({super.key});@override State<AurenBusinessScreen> createState()=>_AurenBusinessScreenState();}
class _AurenBusinessScreenState extends State<AurenBusinessScreen>{
 final _repo=BusinessRepository(); final _search=TextEditingController(); String _category='All';
 static const cats=['All','Retail','Food','Services','Technology','Manufacturing','Education','Travel','Creative','Agriculture','Other'];
 @override void dispose(){_search.dispose();super.dispose();}
 void _create(){if(FirebaseAuth.instance.currentUser==null)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>const AurenBusinessCreateScreen()));}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Business'),actions:[IconButton(tooltip:'Core 5 AI',onPressed:()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;final snapshot=await AurenCoreFiveRepository().load(uid);if(!context.mounted)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>MessengerScreen(initialPrompt:snapshot.toPrompt())));},icon:const Icon(Icons.hub_outlined)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'حلّل احتياجي واقترح لي شركات ومتاجر وخدمات مناسبة، مع سبب الترشيح والخطوة التالية.'))),icon:const Icon(Icons.auto_awesome)),
IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'ضع لي خطة نمو لنشاط Business داخل AUREN: العملاء المستهدفون، المنتجات أو الخدمات، التسويق، الشراكات، والفرصة التالية.'))),icon:const Icon(Icons.trending_up)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AurenSavedBusinessesScreen())),icon:const Icon(Icons.bookmarks_outlined)),IconButton(onPressed:_create,icon:const Icon(Icons.add_business_outlined))]),body:Column(children:[
 Padding(padding:const EdgeInsets.fromLTRB(16,12,16,8),child:TextField(controller:_search,onChanged:(_)=>setState((){}),decoration:InputDecoration(hintText:'ابحث عن شركة، متجر أو خدمة...',prefixIcon:const Icon(Icons.search),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16))))),
 SizedBox(height:48,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,itemCount:cats.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ChoiceChip(label:Text(cats[i]),selected:_category==cats[i],onSelected:(_)=>setState(()=>_category=cats[i])))),
 Expanded(child:StreamBuilder<List<AurenBusiness>>(stream:_repo.watchPublic(query:_search.text,category:_category),builder:(context,s){if(s.hasError)return Center(child:Text('حدث خطأ: $s'));if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const Center(child:Text('لا توجد نتائج بعد.'));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:s.data!.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_Card(b:s.data![i]);})),
 ]),floatingActionButton:FloatingActionButton.extended(onPressed:_create,icon:const Icon(Icons.add),label:const Text('أضف Business')));
}
class _Card extends StatelessWidget{final AurenBusiness b;const _Card({required this.b});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>AurenBusinessDetailScreen(business:b))),leading:CircleAvatar(backgroundImage:b.imageUrl.isEmpty?null:NetworkImage(b.imageUrl),child:b.imageUrl.isEmpty?const Icon(Icons.storefront_outlined):null),title:Row(children:[Expanded(child:Text(b.name,maxLines:1,overflow:TextOverflow.ellipsis)),if(b.verified)const Icon(Icons.verified,size:17)]),subtitle:Text([b.category,b.city,b.country,b.description].where((x)=>x.isNotEmpty).join(' • ')),trailing:const Icon(Icons.chevron_right)));}
class AurenBusinessCreateScreen extends StatefulWidget{const AurenBusinessCreateScreen({super.key});@override State<AurenBusinessCreateScreen> createState()=>_AurenBusinessCreateScreenState();}
class _AurenBusinessCreateScreenState extends State<AurenBusinessCreateScreen>{
 final form=GlobalKey<FormState>();final n=TextEditingController(),d=TextEditingController(),city=TextEditingController(),country=TextEditingController(),phone=TextEditingController(),web=TextEditingController(),img=TextEditingController();String cat='Services',type='Company';bool saving=false;
 static const types=['Company','Store','Restaurant','Freelancer','Service Provider','Factory','Farm','Creator Business','NGO/Organization'];
 @override void dispose(){for(final c in [n,d,city,country,phone,web,img])c.dispose();super.dispose();}
 Future<void> save()async{if(!form.currentState!.validate())return;final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;setState(()=>saving=true);try{await BusinessRepository().create(ownerId:uid,name:n.text,description:d.text,category:cat,city:city.text,country:country.text,phone:phone.text,website:web.text,imageUrl:img.text,businessType:type);if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر الحفظ: $e')));}finally{if(mounted)setState(()=>saving=false);}}
 Widget f(TextEditingController c,String l,{bool req=false,int lines=1})=>TextFormField(controller:c,maxLines:lines,decoration:InputDecoration(labelText:l),validator:req?(v)=>v==null||v.trim().isEmpty?'مطلوب':null:null);
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Create Business')),body:Form(key:form,child:ListView(padding:const EdgeInsets.all(20),children:[f(n,'اسم النشاط',req:true),f(d,'وصف النشاط',lines:4),DropdownButtonFormField(value:cat,items:cats.where((x)=>x!='All').map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>cat=v!),decoration:const InputDecoration(labelText:'التصنيف')),DropdownButtonFormField(value:type,items:types.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>type=v!),decoration:const InputDecoration(labelText:'نوع النشاط')),f(city,'المدينة'),f(country,'الدولة'),f(phone,'الهاتف'),f(web,'الموقع الإلكتروني'),f(img,'رابط صورة/شعار'),const SizedBox(height:20),FilledButton(onPressed:saving?null:save,child:Text(saving?'جاري الحفظ...':'إنشاء النشاط'))])));}
}
