import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../core/models/business.dart';
import '../../../services/business/business_repository.dart';
class AurenBusinessDetailScreen extends StatelessWidget {
 final AurenBusiness business;
 const AurenBusinessDetailScreen({super.key,required this.business});
 @override Widget build(BuildContext context){
  final own=FirebaseAuth.instance.currentUser?.uid==business.ownerId;
  return Scaffold(appBar:AppBar(title:const Text('Business'),actions:[if(own)IconButton(onPressed:()async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('حذف النشاط؟'),content:const Text('لا يمكن التراجع عن هذا الإجراء.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حذف'))]));if(ok==true){await BusinessRepository().delete(business.id);if(context.mounted)Navigator.pop(context);}},icon:const Icon(Icons.delete_outline))]),body:ListView(padding:const EdgeInsets.all(20),children:[if(business.imageUrl.isNotEmpty)ClipRRect(borderRadius:BorderRadius.circular(20),child:Image.network(business.imageUrl,height:220,fit:BoxFit.cover)),const SizedBox(height:16),Row(children:[Expanded(child:Text(business.name,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold))),if(business.verified)const Icon(Icons.verified)]),const SizedBox(height:8),Chip(label:Text(business.category)),if(business.description.isNotEmpty)Padding(padding:const EdgeInsets.only(top:16),child:Text(business.description)),if(business.city.isNotEmpty||business.country.isNotEmpty)ListTile(leading:const Icon(Icons.location_on_outlined),title:const Text('الموقع'),subtitle:Text([business.city,business.country].where((x)=>x.isNotEmpty).join(' • '))),if(business.phone.isNotEmpty)ListTile(leading:const Icon(Icons.phone_outlined),title:const Text('الهاتف'),subtitle:Text(business.phone)),if(business.website.isNotEmpty)ListTile(leading:const Icon(Icons.language),title:const Text('الموقع الإلكتروني'),subtitle:Text(business.website)),const SizedBox(height:16),FilledButton.icon(onPressed:own?null:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('سنربط التواصل المباشر بالـ Messenger في الدفعة التالية.'))),icon:const Icon(Icons.chat_bubble_outline),label:const Text('تواصل مع Business'))]) );
 }
}
