import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';
import '../../../core/models/entertainment.dart';
import '../../../services/entertainment/entertainment_repository.dart';
import 'entertainment_detail_screen.dart';
import 'auren_sports_detail_screen.dart';

class AurenSportsEntertainmentScreen extends StatefulWidget {
  const AurenSportsEntertainmentScreen({super.key});
  @override State<AurenSportsEntertainmentScreen> createState() => _AurenSportsEntertainmentScreenState();
}
class _AurenSportsEntertainmentScreenState extends State<AurenSportsEntertainmentScreen> {
  final _repo = EntertainmentRepository(); String _query = ''; String _sport = 'الكل'; String _resource = 'games'; String _country = ''; String _leagueId = ''; String _season = ''; List<Map<String,dynamic>> _directory = []; bool _loadingDirectory = false; List<Map<String,dynamic>> _remote = []; bool _loadingRemote = false;
  static const _sports = ['الكل', 'Football', 'Basketball', 'Tennis', 'Cricket', 'Baseball', 'Hockey', 'Handball', 'Volleyball', 'Rugby', 'MMA', 'Formula 1', 'NFL', 'Other'];
  Future<void> _loadDirectory() async { setState(() => _loadingDirectory = true); try { final r = await FirebaseFunctions.instance.httpsCallable('searchAurenSports').call({'query': _query, 'sport': _sport == 'الكل' ? 'football' : _sport.toLowerCase().replaceAll(' ', ''), 'resource': _resource, 'country': _country, 'leagueId': _leagueId, 'season': _season}); final data = Map<String,dynamic>.from(r.data as Map); if (mounted) setState(() => _directory = List<Map<String,dynamic>>.from(data['results'] ?? const [])); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('تعذر تحميل البيانات: $e'))); } finally { if (mounted) setState(() => _loadingDirectory = false); } }
  Future<void> _loadRemote() async { setState(() => _loadingRemote = true); try { final r = await FirebaseFunctions.instance.httpsCallable('searchAurenSports').call({'query': _query, 'sport': _sport == 'الكل' ? 'football' : _sport.toLowerCase().replaceAll(' ', '')}); final data = Map<String,dynamic>.from(r.data as Map); if (data['status'] == 'ok') setState(() => _remote = List<Map<String,dynamic>>.from(data['results'] ?? const [])); if (data['status'] == 'not_configured' && mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('مصدر الرياضة يحتاج API key في Firebase Functions.'))); } catch (e) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('تعذر جلب الرياضة: $e'))); } finally { if (mounted) setState(() => _loadingRemote = false); } }
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: Theme.of(context).colorScheme.surface, body: StreamBuilder<List<AurenEntertainmentItem>>(stream: _repo.watchItems(), builder: (context, snapshot) {
    if (snapshot.hasError) return Center(child: Text('تعذر تحميل الرياضة: '+snapshot.error.toString()));
    if (snapshot.connectionState == ConnectionState.waiting) return const Center(child: CircularProgressIndicator());
    final items = (snapshot.data ?? const <AurenEntertainmentItem>[]).where((item) {
      final text = ('${item.title} ${item.description} ${item.type} ${item.genres.join(' ')}').toLowerCase(); final q = _query.trim().toLowerCase();
      final sports = text.contains('sport') || text.contains('football') || text.contains('soccer') || text.contains('basketball') || text.contains('tennis') || text.contains('cricket') || item.type.toLowerCase().contains('sports');
      return sports && (_sport == 'الكل' || text.contains(_sport.toLowerCase())) && (q.isEmpty || text.contains(q));
    }).toList();
    return CustomScrollView(slivers: [SliverToBoxAdapter(child: Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(borderRadius: BorderRadius.circular(24), gradient: LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors: [Theme.of(context).colorScheme.primary, Theme.of(context).colorScheme.secondary])), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.16),shape:BoxShape.circle),child:const Icon(Icons.sports_score,color:Colors.white)),const Spacer(),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.14),borderRadius:BorderRadius.circular(18)),child:const Text('GLOBAL SPORTS',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,fontSize:11)))]),const SizedBox(height:18),const Text('Sports, بطريقة AUREN',style:TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text('المباراة، البطولة، الفريق واللاعب في تجربة واحدة.',style:TextStyle(color:Colors.white.withValues(alpha:.88),fontSize:14)),])),
      const SizedBox(height: 14), Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22)),child: Padding(padding:const EdgeInsets.all(14),child: Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('استكشف الرياضة',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:10), TextField(decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'ابحث عن فريق، مباراة، دوري أو رياضة'), onChanged: (v) => setState(() => _query = v))),
      const SizedBox(height: 10), SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: ['games','leagues','teams','standings','players','team_stats','game_details'].map((r) => Padding(padding: const EdgeInsetsDirectional.only(end: 8), child: ChoiceChip(label: Text(r), selected: _resource == r, onSelected: (_) => setState(() => _resource = r))).toList()))), const SizedBox(height: 8), Row(children: [Expanded(child: TextField(decoration: const InputDecoration(labelText: 'Country'), onChanged: (v)=>_country=v)), const SizedBox(width: 8), Expanded(child: TextField(decoration: const InputDecoration(labelText: 'League ID'), onChanged: (v)=>_leagueId=v)), const SizedBox(width: 8), Expanded(child: TextField(decoration: const InputDecoration(labelText: 'Season'), onChanged: (v)=>_season=v))]), const SizedBox(height: 8), FilledButton.icon(onPressed: _loadingDirectory ? null : _loadDirectory, icon: _loadingDirectory ? const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)) : const Icon(Icons.account_tree), label: const Text('استكشاف البطولات والفرق والترتيب واللاعبين')), if (_directory.isNotEmpty) ...[const SizedBox(height: 10), ..._directory.map((x)=>Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),child:ListTile(title:Text((x['name'] ?? x['title'] ?? '').toString(),style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text((x['country'] ?? '').toString()+' • '+(x['season'] ?? '').toString()+' • '+(x['source'] ?? '').toString()),trailing:const Icon(Icons.arrow_forward_ios,size:15),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AurenSportsDetailScreen(sport:_sport == 'الكل' ? 'football' : _sport.toLowerCase().replaceAll(' ', ''),resource:_resource,data:x))))))], const SizedBox(height: 10), SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: _sports.map((s) => Padding(padding: const EdgeInsetsDirectional.only(end: 8), child: ChoiceChip(label: Text(s), selected: _sport == s, onSelected: (_) => setState(() => _sport = s)))).toList())),
      const SizedBox(height: 8), SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:['games','leagues','teams','standings','players','team_stats','game_details'].map((r)=>Padding(padding:const EdgeInsetsDirectional.only(end:8),child:ChoiceChip(label:Text(r),selected:false,onSelected:(_){setState((){});}))).toList())), const SizedBox(height: 10), FilledButton.icon(onPressed: _loadingRemote ? null : _loadRemote, icon: _loadingRemote ? const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)) : const Icon(Icons.cloud_download), label: const Text('جلب المباريات من المصدر الموثوق')), if (_remote.isNotEmpty) ...[const SizedBox(height:12), const Text('مباريات من المصدر الموثوق',style:TextStyle(fontWeight:FontWeight.w800)), ..._remote.map((x)=>Card(child:ListTile(title:Text(x['title']?.toString()??''),subtitle:Text('${x['league']??''} • ${x['date']??''} • ${x['source']??''}'),leading:const Icon(Icons.sports_soccer))))],
      const SizedBox(height: 14), if (items.isEmpty) const Card(child: Padding(padding: EdgeInsets.all(20), child: Text('لا توجد عناصر رياضية منشورة حالياً. عند إضافة بيانات رياضية إلى AUREN ستظهر هنا تلقائياً.'))) else ...items.map((item) => Card(child: ListTile(leading: item.imageUrl.isEmpty ? const CircleAvatar(child: Icon(Icons.sports_soccer)) : CircleAvatar(backgroundImage: NetworkImage(item.imageUrl)), title: Text(item.title), subtitle: Text('${item.type} • ${item.description}', maxLines: 2, overflow: TextOverflow.ellipsis), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => AurenEntertainmentDetailScreen(itemId: item.id))))))
    )))]);
  });
}