import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

import '../../search/presentation/global_search_screen.dart';
import 'entertainment_detail_screen.dart';
import '../../../services/entertainment/entertainment_repository.dart';
import '../../../core/models/entertainment.dart';
import '../../messenger/presentation/messenger_screen.dart';

class AurenAURENEntertainmentScreen extends StatefulWidget{const AurenAURENEntertainmentScreen({super.key});@override State<AurenAURENEntertainmentScreen> createState()=>_EntertainmentState();}
class _EntertainmentState extends State<AurenAURENEntertainmentScreen>{final repo=EntertainmentRepository();String query='';String? type;
@override Widget build(BuildContext context){final uid=FirebaseAuth.instance.currentUser?.uid;return Scaffold(appBar:AppBar(title:const Text('AUREN Entertainment'),actions:[IconButton(icon:const Icon(Icons.search),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AurenGlobalSearchScreen())),),IconButton(icon:const Icon(Icons.auto_awesome),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'اكتشف لي محتوى ترفيهي يناسب ذوقي ووقتي واهتماماتي.'))))]),body:StreamBuilder<List<AurenEntertainmentItem>>(stream:repo.watchItems(type:type),builder:(context,s){if(s.hasError)return Center(child:Text('تعذر تحميل المحتوى: '+s.error.toString()));if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final items=s.data??const <AurenEntertainmentItem>[];return StreamBuilder<Set<String>>(stream:uid==null?const Stream<Set<String>>.empty():repo.watchSavedIds(uid),builder:(context,ss){final saved=ss.data??{};final q=query.toLowerCase();final filtered=items.where((i)=>q.isEmpty||(i.title+' '+i.description+' '+i.type).toLowerCase().contains(q)).toList();return ListView(padding:const EdgeInsets.all(16),children:[const ListTile(contentPadding:EdgeInsets.zero,leading:Icon(Icons.movie,size:34),title:Text('Entertainment',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),subtitle:Text('Global Series، Anime، Podcasts، Books و AUREN World.')),TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن محتوى'),onChanged:(v)=>setState(()=>query=v)),const SizedBox(height:8),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[null,'Global Series','Anime','Podcast','Book'].map((x)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(x??'All'),selected:type==x,onSelected:(_)=>setState(()=>type=x))).toList()))),const SizedBox(height:12),...filtered.map((item)=>Card(child:ListTile(leading:item.imageUrl.isEmpty?const CircleAvatar(child:Icon(Icons.play_arrow)):CircleAvatar(backgroundImage:NetworkImage(item.imageUrl)),title:Text(item.title),subtitle:Text(item.type+'\n'+item.description),isThreeLine:true,trailing:uid==null?null:IconButton(icon:Icon(saved.contains(item.id)?Icons.bookmark:Icons.bookmark_border),onPressed:()=>saved.contains(item.id)?repo.unsave(uid,item.id):repo.save(uid,item.id)),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AurenEntertainmentDetailScreen(itemId:item.id)))))])});});}}