name: auren
description: AUREN — Together, We Build.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  cloud_functions: ^6.1.0
  http: ^1.6.0

flutter:
  uses-material-design: true
