import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../services/personal_ai/export_ai_service.dart';
import '../../messenger/presentation/messenger_screen.dart';
class AurenExportAiScreen extends StatefulWidget{const AurenExportAiScreen({super.key});@override State<AurenExportAiScreen> createState()=>_AurenExportAiScreenState();}
class _AurenExportAiScreenState extends State<AurenExportAiScreen>{
 final p=TextEditingController(),d=TextEditingController(); String mode='بحري'; AurenExportPlan? plan; bool loading=false;
 Future<void> buildPlan()async{final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null||p.text.trim().isEmpty||d.text.trim().isEmpty)return;setState(()=>loading=true);try{final x=await ExportAiService().build(uid,product:p.text,destination:d.text,mode:mode);if(mounted)setState(()=>plan=x);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر إنشاء الخطة: '+e.toString())));}finally{if(mounted)setState(()=>loading=false);}}
 @override void dispose(){p.dispose();d.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Export AI')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('Export AI',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:6),const Text('حوّل فكرة التصدير إلى قائمة عمل أولية، مع إبقاء التحقق القانوني والجمركي بيد الجهات المختصة.'),const SizedBox(height:16),TextField(controller:p,decoration:const InputDecoration(labelText:'المنتج')),const SizedBox(height:10),TextField(controller:d,decoration:const InputDecoration(labelText:'الدولة المستهدفة')),const SizedBox(height:10),DropdownButtonFormField<String>(value:mode,items:const['بحري','جوي','بري','متعدد الوسائط'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null)setState(()=>mode=x);},decoration:const InputDecoration(labelText:'طريقة النقل')),const SizedBox(height:12),FilledButton.icon(onPressed:loading?null:buildPlan,icon:const Icon(Icons.public),label:Text(loading?'جاري البناء…':'أنشئ خطة التصدير')),if(plan!=null)...[const SizedBox(height:20),Text('خطة التصدير: '+plan!.product+' → '+plan!.destination,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...plan!.steps.asMap().entries.map((e)=>ListTile(leading:CircleAvatar(child:Text('${e.key+1}')),title:Text(e.value))),const Divider(),const Text('قائمة التحقق',style:TextStyle(fontWeight:FontWeight.bold)),...plan!.checks.map((x)=>CheckboxListTile(value:false,onChanged:null,title:Text(x))),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>MessengerScreen(initialPrompt:'حلّل لي خطة تصدير '+plan!.product+' إلى '+plan!.destination+'. لا تنفذ أو ترسل أو تلتزم بأي شيء بدون موافقتي.'))),icon:const Icon(Icons.chat),label:const Text('حلّل الخطة مع AUREN AI'))]]));
}