import 'dart:async';
import 'package:flutter/material.dart';
import '../../../services/auth/auth_service.dart';
import '../../../services/goals/goal_repository.dart';
import '../../../core/models/goal.dart';
import '../../../services/personal_ai/focus_mode_service.dart';
class AurenFocusModeScreen extends StatefulWidget{const AurenFocusModeScreen({super.key});@override State<AurenFocusModeScreen> createState()=>_AurenFocusModeScreenState();}
class _AurenFocusModeScreenState extends State<AurenFocusModeScreen>{final _auth=FirebaseAurenAuthService();final _goals=GoalRepository();final _service=FocusModeService();AurenGoal? _goal;int _minutes=25,_remaining=0;Timer? _timer;
void _start()async{final uid=_auth.currentUserId;if(uid==null||_goal==null)return;await _service.start(uid,goalId:_goal!.id,title:_goal!.title,minutes:_minutes);setState(()=>_remaining=_minutes*60);_timer?.cancel();_timer=Timer.periodic(const Duration(seconds:1),(t){if(_remaining<=1){t.cancel();setState(()=>_remaining=0);}else{setState(()=>_remaining--);}});}
Future<void> _stop()async{final uid=_auth.currentUserId;if(uid!=null)await _service.stop(uid);_timer?.cancel();if(mounted)setState(()=>_remaining=0);}
@override void dispose(){_timer?.cancel();super.dispose();}
@override Widget build(BuildContext context){final uid=_auth.currentUserId;if(uid==null)return const Scaffold(body:Center(child:Text('سجّل الدخول أولاً.')));return Scaffold(appBar:AppBar(title:const Text('Focus Mode')),body:StreamBuilder<List<AurenGoal>>(stream:_goals.watch(uid),builder:(c,s){final active=(s.data??[]).where((g)=>g.status=='active').toList();_goal??=(active.isNotEmpty?active.first:null);return ListView(padding:const EdgeInsets.all(20),children:[const Text('Focus Mode',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('اختَر هدفًا واعمل عليه بدون تشتيت.'),const SizedBox(height:20),DropdownButtonFormField<String>(value:_goal?.id,items:active.map((g)=>DropdownMenuItem(value:g.id,child:Text(g.title))).toList(),onChanged:(id){if(id!=null)setState(()=>_goal=active.firstWhere((g)=>g.id==id));},decoration:const InputDecoration(labelText:'الهدف')),const SizedBox(height:16),DropdownButtonFormField<int>(value:_minutes,items:const [15,25,45,60].map((m)=>DropdownMenuItem(value:m,child:Text('$m دقيقة'))).toList(),onChanged:(v){if(v!=null)setState(()=>_minutes=v);},decoration:const InputDecoration(labelText:'مدة التركيز')),const SizedBox(height:28),Center(child:Text(_remaining==0?'جاهز':(_remaining~/60).toString().padLeft(2,'0')+':'+(_remaining%60).toString().padLeft(2,'0'),style:const TextStyle(fontSize:52,fontWeight:FontWeight.bold))),const SizedBox(height:20),FilledButton.icon(onPressed:_remaining>0?_stop:_start,icon:Icon(_remaining>0?Icons.stop:Icons.play_arrow),label:Text(_remaining>0?'إيقاف':'ابدأ جلسة التركيز'))]);});}}