import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import '../../../services/auth/auth_service.dart';
import '../../../services/social/random_call_service.dart';

class AurenRandomCallScreen extends StatefulWidget {
  final String callId; final bool caller; final String kind; final String otherName;
  const AurenRandomCallScreen({super.key,required this.callId,required this.caller,required this.kind,this.otherName='AUREN User'});
  @override State<AurenRandomCallScreen> createState()=>_AurenRandomCallScreenState();
}
class _AurenRandomCallScreenState extends State<AurenRandomCallScreen>{
  final auth=FirebaseAurenAuthService(),service=AurenRandomCallService();
  final local=RTCVideoRenderer(),remote=RTCVideoRenderer();
  RTCPeerConnection? pc; MediaStream? stream; StreamSubscription<AurenRandomCall?>? callSub; StreamSubscription<QuerySnapshot<Map<String,dynamic>>>? candidateSub;
  final Set<String> receivedCandidateIds=<String>{}; bool muted=false,cameraOff=false,ready=false,ended=false; String state='connecting';
  @override void initState(){super.initState();_start();}
  Future<void> _start()async{try{await local.initialize();await remote.initialize();final uid=auth.currentUserId;if(uid==null)throw StateError('not_authenticated');pc=await createPeerConnection({'iceServers':[{'urls':'stun:stun.l.google.com:19302'}]});pc!.onTrack=(e){if(e.streams.isNotEmpty&&mounted){remote.srcObject=e.streams.first;setState(()=>state='connected');}};pc!.onConnectionState=(s){if(!mounted)return;final v=s.toString().split('.').last;setState(()=>state=v);if(v=='failed'||v=='closed'||v=='disconnected')_finishLocally();};pc!.onIceCandidate=(c) async {if(c.candidate==null||ended)return;await service.addCandidate(widget.callId,senderUid:uid,candidate:RTCandidate(candidate:c.candidate,sdpMid:c.sdpMid,sdpMLineIndex:c.sdpMLineIndex));};stream=await navigator.mediaDevices.getUserMedia({'audio':true,'video':widget.kind=='video'});local.srcObject=stream;for(final t in stream!.getTracks()){await pc!.addTrack(t,stream!);}if(widget.caller){await _startCaller();}else{await _startCallee();}if(mounted)setState(()=>ready=true);}catch(_){if(mounted){setState(()=>state='failed');ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تعذر تشغيل الكاميرا/الميكروفون أو بدء المكالمة.')));}}}
  Future<void> _startCaller()async{final offer=await pc!.createOffer();await pc!.setLocalDescription(offer);final d=await pc!.getLocalDescription();await service.setOffer(widget.callId,{'sdp':d?.sdp,'type':d?.type});_listenForCallChanges();_listenForCandidates();}
  Future<void> _startCallee()async{final call=await service.watch(widget.callId).firstWhere((value)=>value==null||value.offer!=null).timeout(const Duration(seconds:20));if(call==null||call.status=='ended'||call.offer==null)throw StateError('offer_missing');final offer=call.offer!;await pc!.setRemoteDescription(RTCSessionDescription(offer['sdp'] as String,offer['type'] as String));_listenForCandidates();final answer=await pc!.createAnswer();await pc!.setLocalDescription(answer);final d=await pc!.getLocalDescription();await service.answer(widget.callId,{'sdp':d?.sdp,'type':d?.type});_listenForCallChanges();}
  void _listenForCallChanges(){callSub??=service.watch(widget.callId).listen((call)async{if(call==null||ended)return;if(call.status=='ended'){await _finishLocally();return;}if(widget.caller&&call.answer!=null){final current=await pc?.getRemoteDescription();if(current==null){final a=call.answer!;await pc!.setRemoteDescription(RTCSessionDescription(a['sdp'] as String,a['type'] as String));}}});}
  void _listenForCandidates(){candidateSub??=service.watchCandidates(widget.callId).listen((snap)async{final uid=auth.currentUserId;if(uid==null||pc==null||ended)return;for(final change in snap.docChanges){if(receivedCandidateIds.contains(change.doc.id))continue;receivedCandidateIds.add(change.doc.id);final data=change.doc.data();if(data['senderUid']==uid||data['candidate']==null)continue;try{await pc!.addCandidate(RTCIceCandidate(data['candidate'] as String,data['sdpMid'] as String?,(data['sdpMLineIndex'] as num?)?.toInt()));}catch(_){}}});}
  Future<void> _hangUp()async{if(ended)return;ended=true;try{await service.end(widget.callId,auth.currentUserId??'unknown');}catch(_){}if(mounted)Navigator.of(context).pop();}
  Future<void> _finishLocally()async{if(ended)return;ended=true;if(mounted)Navigator.of(context).pop();}
  @override void dispose(){callSub?.cancel();candidateSub?.cancel();for(final t in stream?.getTracks()??<MediaStreamTrack>[]){t.stop();}stream?.dispose();pc?.close();local.dispose();remote.dispose();super.dispose();}
  @override Widget build(BuildContext context){final isVideo=widget.kind=='video';return Scaffold(backgroundColor:Colors.black,appBar:AppBar(title:Text(widget.otherName),backgroundColor:Colors.black),body:Stack(children:[Positioned.fill(child:isVideo?RTCVideoView(remote,objectFit:RTCVideoViewObjectFit.RTCVideoViewObjectFitCover):const Center(child:Icon(Icons.person,color:Colors.white,size:100))),if(isVideo)Positioned(right:16,top:16,width:110,height:160,child:RTCVideoView(local,mirror:true)),if(state!='connected')Positioned(top:16,left:16,child:DecoratedBox(decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(16)),child:Padding(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),child:Text(state=='ringing'?'جاري الاتصال…':state,style:const TextStyle(color:Colors.white))))),Positioned(bottom:24,left:16,right:16,child:Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[IconButton(onPressed:()=>setState((){muted=!muted;for(final t in stream?.getAudioTracks()??<MediaStreamTrack>[]){t.enabled=!muted;}}),icon:Icon(muted?Icons.mic_off:Icons.mic,color:Colors.white)),IconButton(onPressed:_hangUp,icon:const Icon(Icons.call_end,color:Colors.red,size:38)),if(isVideo)IconButton(onPressed:()=>setState((){cameraOff=!cameraOff;for(final t in stream?.getVideoTracks()??<MediaStreamTrack>[]){t.enabled=!cameraOff;}}),icon:Icon(cameraOff?Icons.videocam_off:Icons.videocam,color:Colors.white))]),),if(!ready)const Center(child:CircularProgressIndicator())]));}
}
