import 'package:cloud_firestore/cloud_firestore.dart';

class AurenStay {
  final String id, ownerId, name, city, country, type, description, currency, status;
  final int priceMinor, guests;
  final DateTime? createdAt;
  const AurenStay({required this.id,required this.ownerId,required this.name,required this.city,required this.country,required this.type,required this.description,required this.currency,required this.priceMinor,required this.guests,required this.status,required this.createdAt});
  factory AurenStay.fromDoc(DocumentSnapshot<Map<String,dynamic>> doc){final d=doc.data()??{};final t=d['createdAt'];return AurenStay(id:doc.id,ownerId:(d['ownerId']??'') as String,name:(d['name']??'') as String,city:(d['city']??'') as String,country:(d['country']??'') as String,type:(d['type']??'hotel') as String,description:(d['description']??'') as String,currency:(d['currency']??'USD') as String,priceMinor:(d['priceMinor']??0) as int,guests:(d['guests']??1) as int,status:(d['status']??'active') as String,createdAt:t is Timestamp?t.toDate():null);}
}
class AurenStayService {
  AurenStayService._(); static final instance=AurenStayService._(); final _db=FirebaseFirestore.instance;
  Stream<List<AurenStay>> watch({String city='',String country=''}){Query<Map<String,dynamic>> q=_db.collection('stays').where('status',isEqualTo:'active').limit(100);return q.snapshots().map((s){final c=city.trim().toLowerCase(),co=country.trim().toLowerCase();return s.docs.map(AurenStay.fromDoc).where((x)=>(c.isEmpty||x.city.toLowerCase()==c)&&(co.isEmpty||x.country.toLowerCase()==co)).toList();});}
  Future<String> create({required String ownerId,required String name,required String city,required String country,required String type,required String description,required String currency,required int priceMinor,required int guests})async{if(ownerId.isEmpty||name.trim().isEmpty||city.trim().isEmpty||country.trim().isEmpty)throw ArgumentError('بيانات مكان الإقامة الأساسية مطلوبة.');if(!['hotel','apartment','villa','hostel','resort','guesthouse'].contains(type))throw ArgumentError('نوع الإقامة غير صالح.');if(priceMinor<0||guests<1||guests>50)throw ArgumentError('السعر أو عدد الضيوف غير صالح.');final ref=_db.collection('stays').doc();await ref.set({'ownerId':ownerId,'name':name.trim(),'city':city.trim(),'country':country.trim(),'type':type,'description':description.trim(),'currency':currency.trim().toUpperCase(),'priceMinor':priceMinor,'guests':guests,'status':'active','createdAt':FieldValue.serverTimestamp()});return ref.id;}
  Future<String> createBooking({required String uid,required AurenStay stay,required DateTime checkIn,required DateTime checkOut,required int guests})async{if(checkOut.isBefore(checkIn)||checkOut.isAtSameMomentAs(checkIn))throw ArgumentError('تاريخ المغادرة يجب أن يكون بعد الوصول.');if(guests<1||guests>stay.guests)throw ArgumentError('عدد الضيوف يتجاوز السعة.');final ref=_db.collection('stay_bookings').doc();await ref.set({'guestUid':uid,'stayId':stay.id,'ownerId':stay.ownerId,'name':stay.name,'city':stay.city,'checkIn':Timestamp.fromDate(checkIn),'checkOut':Timestamp.fromDate(checkOut),'guests':guests,'currency':stay.currency,'priceMinorPerNight':stay.priceMinor,'status':'requested','createdAt':FieldValue.serverTimestamp()});return ref.id;}
  Stream<QuerySnapshot<Map<String,dynamic>>> watchMyBookings(String uid)=>_db.collection('stay_bookings').where('guestUid',isEqualTo:uid).limit(50).snapshots();
}