import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../services/opportunities/opportunity_repository.dart';
import '../../../core/models/opportunity.dart';
import '../../messenger/presentation/messenger_screen.dart';

class AurenOpportunitiesScreen extends StatefulWidget{const AurenOpportunitiesScreen({super.key});@override State<AurenOpportunitiesScreen> createState()=>_AurenOpportunitiesScreenState();}
class _AurenOpportunitiesScreenState extends State<AurenOpportunitiesScreen>{
 final repo=OpportunityRepository();final search=TextEditingController();String type='All';
 static const types=['All','Job','Freelance','Project','Partnership','Supplier','Investment','Learning','Volunteer'];
 @override void dispose(){search.dispose();super.dispose();}
 @override Widget build(BuildContext c){final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return const Scaffold(body:Center(child:Text('سجّل الدخول لاكتشاف الفرص.')));return Scaffold(appBar:AppBar(title:const Text('AUREN Opportunities'),actions:[IconButton(tooltip:'طلباتي',icon:const Icon(Icons.assignment_outlined),onPressed:()=>_myApplications(c,uid)),IconButton(tooltip:'طلبات فرصي',icon:const Icon(Icons.people_alt_outlined),onPressed:()=>_receivedApplications(c,uid)),IconButton(icon:const Icon(Icons.auto_awesome),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'حلّل أهدافي ومهاراتي واقترح لي فرصاً مناسبة مع سبب المطابقة والخطوة التالية.'))))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_create(c,uid),icon:const Icon(Icons.add),label:const Text('أضف فرصة')),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن فرصة أو مهارة...',border:OutlineInputBorder()))),SizedBox(height:48,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:16),itemCount:types.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ChoiceChip(label:Text(types[i]),selected:type==types[i],onSelected:(_)=>setState(()=>type=types[i])))),Expanded(child:StreamBuilder<List<AurenOpportunity>>(stream:repo.watchOpen(query:search.text,type:type),builder:(c,s){if(s.hasError)return Center(child:Text('تعذر تحميل الفرص: '+s.error.toString()));if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=s.data!;if(list.isEmpty)return const Center(child:Text('لا توجد فرص مطابقة حالياً.'));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_card(c,list[i],uid);}))]));}
 Widget _card(BuildContext c,AurenOpportunity o,String uid)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.work_outline)),title:Text(o.title),subtitle:Text([o.type,o.category,o.city,o.country].where((x)=>x.isNotEmpty).join(' • ')),onTap:()=>_details(c,o,uid)));
 Future<void> _details(BuildContext c,AurenOpportunity o,String uid)async{final applied=await repo.hasApplied(uid,o.id);if(!c.mounted)return;showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,20+MediaQuery.of(c).viewInsets.bottom),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(o.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(o.description),if(o.skills.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Wrap(spacing:6,children:o.skills.map((x)=>Chip(label:Text(x))).toList())),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton.icon(onPressed:applied||uid==o.ownerId?null:()=>_apply(c,o,uid),icon:Icon(applied?Icons.check:Icons.send),label:Text(applied?'تم التقديم':'تقديم'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'جهز لي رسالة تقديم احترافية لهذه الفرصة.'))),icon:const Icon(Icons.auto_awesome),label:const Text('AI')))])])));}
 Future<void> _apply(BuildContext c,AurenOpportunity o,String uid)async{final note=TextEditingController();final ok=await showDialog<bool>(context:c,builder:(ctx)=>AlertDialog(title:const Text('التقديم على الفرصة'),content:TextField(controller:note,maxLines:5,maxLength:2000,decoration:const InputDecoration(hintText:'اكتب ملاحظة لصاحب الفرصة (اختياري)')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('إرسال التقديم'))]));if(ok!=true)return;try{await repo.apply(uid:uid,opportunity:o,note:note.text);if(c.mounted)Navigator.pop(c);if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('تم إرسال التقديم بنجاح.')));}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('تعذر التقديم: $e')));}finally{note.dispose();}}
 void _myApplications(BuildContext c,String uid)=>showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>SizedBox(height:MediaQuery.of(c).size.height*.75,child:StreamBuilder<List<AurenOpportunityApplication>>(stream:repo.watchMyApplications(uid),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const Center(child:Text('لا توجد طلبات تقديم بعد.'));return ListView(padding:const EdgeInsets.all(16),children:[const Text('طلباتي',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...s.data!.map((a)=>ListTile(title:Text(a.title),subtitle:Text(a.note.isEmpty?'بدون ملاحظة':a.note),trailing:Text(a.status)))]);})));
 void _receivedApplications(BuildContext c,String uid)=>showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>SizedBox(height:MediaQuery.of(c).size.height*.75,child:StreamBuilder<List<AurenOpportunityApplication>>(stream:repo.watchReceived(uid),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const Center(child:Text('لا توجد طلبات مستلمة.'));return ListView(padding:const EdgeInsets.all(16),children:[const Text('طلبات فرصي',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...s.data!.map((a)=>Card(child:ListTile(title:Text(a.title),subtitle:Text(a.note.isEmpty?'بدون ملاحظة':a.note),trailing:PopupMenuButton<String>(onSelected:(v)async{try{await repo.updateApplicationStatus(applicantId:a.applicantId,opportunityId:a.opportunityId,status:v);}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('تعذر تحديث الطلب: $e')));}},itemBuilder:(_)=>const [PopupMenuItem(value:'accepted',child:Text('قبول')),PopupMenuItem(value:'rejected',child:Text('رفض'))]))))]);})));
 Future<void> _create(BuildContext c,String uid)async{final title=TextEditingController(),desc=TextEditingController(),skills=TextEditingController(),city=TextEditingController(),country=TextEditingController();String t='Job';final ok=await showDialog<bool>(context:c,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(title:const Text('إضافة فرصة'),content:SingleChildScrollView(child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:desc,maxLines:4,decoration:const InputDecoration(labelText:'الوصف')),DropdownButtonFormField<String>(value:t,items:types.where((x)=>x!='All').map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>t=v!),decoration:const InputDecoration(labelText:'النوع')),TextField(controller:skills,decoration:const InputDecoration(labelText:'Skills (comma separated)')),TextField(controller:city,decoration:const InputDecoration(labelText:'المدينة')),TextField(controller:country,decoration:const InputDecoration(labelText:'الدولة'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('إنشاء'))]));if(ok==true&&title.text.trim().isNotEmpty)await repo.create(ownerId:uid,title:title.text,description:desc.text,type:t,category:'General',city:city.text,country:country.text,skills:skills.text.split(','));for(final x in[title,desc,skills,city,country])x.dispose();}
}