import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../services/opportunities/opportunity_repository.dart';
import '../../../core/models/opportunity.dart';
import '../../messenger/presentation/messenger_screen.dart';

class AurenOpportunitiesScreen extends StatefulWidget{const AurenOpportunitiesScreen({super.key});@override State<AurenOpportunitiesScreen> createState()=>_AurenOpportunitiesScreenState();}
class _AurenOpportunitiesScreenState extends State<AurenOpportunitiesScreen>{
 final repo=OpportunityRepository();final search=TextEditingController();String type='All';
 static const types=['All','Job','Freelance','Project','Partnership','Supplier','Investment','Learning','Volunteer'];
 @override void dispose(){search.dispose();super.dispose();}
 @override Widget build(BuildContext c){final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return const Scaffold(body:Center(child:Text('سجّل الدخول لاكتشاف الفرص.')));return Scaffold(appBar:AppBar(title:const Text('AUREN Opportunities'),actions:[IconButton(icon:const Icon(Icons.auto_awesome),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'حلّل أهدافي ومهاراتي واقترح لي فرصاً مناسبة مع سبب المطابقة والخطوة التالية.'))))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_create(c,uid),icon:const Icon(Icons.add),label:const Text('أضف فرصة')),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن فرصة أو مهارة...',border:OutlineInputBorder()))),SizedBox(height:48,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:16),itemCount:types.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ChoiceChip(label:Text(types[i]),selected:type==types[i],onSelected:(_)=>setState(()=>type=types[i])))),Expanded(child:StreamBuilder<List<AurenOpportunity>>(stream:repo.watchOpen(query:search.text,type:type),builder:(c,s){if(s.hasError)return Center(child:Text('تعذر تحميل الفرص: '+s.error.toString()));if(!s.hasData)return const Center(child:CircularProgressIndicator());final list=s.data!;if(list.isEmpty)return const Center(child:Text('لا توجد فرص مطابقة حالياً.'));return ListView.separated(padding:const EdgeInsets.all(16),itemCount:list.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i)=>_card(c,list[i]);}))]));}
 Widget _card(BuildContext c,AurenOpportunity o)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.work_outline)),title:Text(o.title),subtitle:Text([o.type,o.category,o.city,o.country].where((x)=>x.isNotEmpty).join(' • ')),onTap:()=>showModalBottomSheet(context:c,builder:(_)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(o.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(o.description),if(o.skills.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Wrap(spacing:6,children:o.skills.map((x)=>Chip(label:Text(x))).toList())),const SizedBox(height:12),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>MessengerScreen(initialPrompt:'ساعدني أجهز رسالة تقديم لهذه الفرصة: '+o.title+'\n'+o.description))),icon:const Icon(Icons.auto_awesome),label:const Text('AI Application'))]))));
 Future<void> _create(BuildContext c,String uid)async{final title=TextEditingController(),desc=TextEditingController(),skills=TextEditingController(),city=TextEditingController(),country=TextEditingController();String t='Job';final ok=await showDialog<bool>(context:c,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(title:const Text('إضافة فرصة'),content:SingleChildScrollView(child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:desc,maxLines:4,decoration:const InputDecoration(labelText:'الوصف')),DropdownButtonFormField<String>(value:t,items:types.where((x)=>x!='All').map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>t=v!),decoration:const InputDecoration(labelText:'النوع')),TextField(controller:skills,decoration:const InputDecoration(labelText:'Skills (comma separated)')),TextField(controller:city,decoration:const InputDecoration(labelText:'المدينة')),TextField(controller:country,decoration:const InputDecoration(labelText:'الدولة'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('إنشاء'))]));if(ok==true&&title.text.trim().isNotEmpty)await repo.create(ownerId:uid,title:title.text,description:desc.text,type:t,category:'General',city:city.text,country:country.text,skills:skills.text.split(','));for(final x in[title,desc,skills,city,country])x.dispose();}
}