import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';

class AurenCreatorTopContent{final String id,title;final int likes,comments;const AurenCreatorTopContent({required this.id,required this.title,required this.likes,required this.comments});int get engagement=>likes+comments;}
class AurenCreatorPlanItem{final String id,title,format,status;final DateTime? scheduledAt;final String aiDraft;const AurenCreatorPlanItem({required this.id,required this.title,required this.format,required this.status,this.scheduledAt,this.aiDraft=''});}
class AurenCreatorGrowthSummary{final int posts,likes,comments,mediaPosts,scheduled; final double engagementRate;const AurenCreatorGrowthSummary({required this.posts,required this.likes,required this.comments,required this.mediaPosts,required this.scheduled,required this.engagementRate});double get avgLikes=>posts==0?0:likes/posts;}
class AurenCreatorGrowthRepository{
 final FirebaseFirestore _db;AurenCreatorGrowthRepository({FirebaseFirestore? firestore}):_db=firestore??FirebaseFirestore.instance;
 CollectionReference<Map<String,dynamic>> _posts()=>_db.collection('posts');CollectionReference<Map<String,dynamic>> _plans(String u)=>_db.collection('users').doc(u).collection('creator_plan');
 Future<AurenCreatorGrowthSummary> summary(String uid)async{final u=uid.trim();if(u.isEmpty||u.length>128)throw ArgumentError('Invalid uid.');final s=await _posts().where('authorId',isEqualTo:u).limit(100).get();var likes=0,comments=0,media=0;for(final d in s.docs){final m=d.data();likes+=(m['likes']as num?)?.toInt()??0;comments+=(m['comments']as num?)?.toInt()??0;if((m['mediaUrl']??'').toString().trim().isNotEmpty)media++;}final p=await _plans(u).where('status',isEqualTo:'scheduled').limit(50).get();return AurenCreatorGrowthSummary(posts:s.size,likes:likes,comments:comments,mediaPosts:media,scheduled:p.size,engagementRate:s.docs.isEmpty?0:((likes+comments)/s.size));}
 Stream<List<AurenCreatorPlanItem>> watchPlan(String uid){final u=uid.trim();if(u.isEmpty)return const Stream.empty();return _plans(u).limit(50).snapshots().map((s){final list=s.docs.map((d){final m=d.data();final r=m['scheduledAt'];final at=r is Timestamp?r.toDate():DateTime.tryParse(r?.toString()??'');return AurenCreatorPlanItem(id:d.id,title:m['title']?.toString()??'',format:m['format']?.toString()??'post',status:m['status']?.toString()??'draft',scheduledAt:at,aiDraft:m['aiDraft']?.toString()??'');}).toList();list.sort((a,b)=>(a.scheduledAt??DateTime.fromMillisecondsSinceEpoch(0)).compareTo(b.scheduledAt??DateTime.fromMillisecondsSinceEpoch(0)));return list;});}
 Future<String> addPlan({required String uid,required String title,required String format,DateTime? scheduledAt})async{final u=uid.trim(),t=title.trim(),f=format.trim();if(u.isEmpty||u.length>128)throw ArgumentError('Invalid uid.');if(t.isEmpty||t.length>200)throw ArgumentError('Title must be 1-200 characters.');if(!{'post','short','video','live','audio'}.contains(f))throw ArgumentError('Unsupported format.');if(scheduledAt!=null&&scheduledAt.isBefore(DateTime.now().subtract(const Duration(minutes:1))))throw ArgumentError('Schedule time must be future.');final r=_plans(u).doc();await r.set({'title':t,'format':f,'status':scheduledAt==null?'draft':'scheduled','scheduledAt':scheduledAt==null?null:Timestamp.fromDate(scheduledAt.toUtc()),'createdAt':FieldValue.serverTimestamp()});return r.id;}
 Future<void> saveAiDraft({required String uid,required String planId,required String draft})async{final u=uid.trim(),p=planId.trim(),d=draft.trim();if(u.isEmpty||u.length>128||p.isEmpty||p.length>128)throw ArgumentError('Creator and plan id required.');if(d.isEmpty||d.length>12000)throw ArgumentError('AI draft must be 1-12000 characters.');await _plans(u).doc(p).update({'aiDraft':d});}
 Future<String> publishAiDraftAsShort({required String uid,required String planId})async{final u=uid.trim(),p=planId.trim();if(u.isEmpty||p.isEmpty)throw ArgumentError('Creator and plan id required.');final callable=FirebaseFunctions.instance.httpsCallable('publishCreatorPlanAsShort');final result=await callable.call({'planId':p});final data=result.data;final id=data is Map?data['shortId']?.toString():null;if(id==null||id.isEmpty)throw StateError('Short publish did not return an id.');return id;}
 Future<List<AurenCreatorTopContent>> topContent(String uid,{int limit=5})async{final u=uid.trim();if(u.isEmpty||u.length>128)throw ArgumentError('Invalid creator uid.');final n=limit.clamp(1,10);final snap=await _posts().where('authorId',isEqualTo:u).limit(100).get();final items=snap.docs.map((d){final m=d.data();return AurenCreatorTopContent(id:d.id,title:(m['text']??'').toString().trim(),likes:(m['likes']as num?)?.toInt()??0,comments:(m['comments']as num?)?.toInt()??0);}).toList();items.sort((a,b)=>(b.likes+b.comments).compareTo(a.likes+a.comments));return items.take(n).toList();}
 Future<String> publishAiDraft({required String uid,required String planId})async{final u=uid.trim(),p=planId.trim();if(u.isEmpty||p.isEmpty)throw ArgumentError('Creator and plan id required.');final planRef=_plans(u).doc(p);final snap=await planRef.get();if(!snap.exists)throw StateError('Plan not found.');final data=snap.data()??{};if(data['status']=='published')throw StateError('Plan already published.');final draft=data['aiDraft']?.toString().trim()??'';if(draft.isEmpty)throw StateError('Create an AI draft first.');final post=_posts().doc();await post.set({'authorId':u,'text':draft,'mediaUrl':'','mediaType':'none','contentType':'creator','contextLabel':'Creator','actionLabel':'','communityId':'','createdAt':DateTime.now().toUtc().toIso8601String(),'likes':0,'comments':0,'searchText':draft.toLowerCase()});await planRef.update({'status':'published','publishedPostId':post.id});return post.id;}
 Future<void> deletePlan(String uid,String id)async{final u=uid.trim(),p=id.trim();if(u.isEmpty||p.isEmpty)throw ArgumentError('Creator and plan id required.');await _plans(u).doc(p).delete();}
}