import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../../../services/marketplace/marketplace_commerce_repository.dart';
import '../../../services/marketplace/marketplace_repository.dart';

class AurenMarketplaceCommerceScreen extends StatelessWidget {
  const AurenMarketplaceCommerceScreen({super.key});
  @override Widget build(BuildContext context){
    final uid=FirebaseAuth.instance.currentUser?.uid;
    if(uid==null)return const Scaffold(body:Center(child:Text('سجّل الدخول أولاً.')));
    final repo=MarketplaceCommerceRepository();
    return Scaffold(appBar:AppBar(title:const Text('Marketplace Center')),body:ListView(padding:const EdgeInsets.all(16),children:[
      const Text('التجارة والطلبات',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),
      const SizedBox(height:12),
      _section(context,'🛒 السلة','المنتجات المحفوظة للشراء',()=>_cart(context,repo,uid)),
      _section(context,'📦 طلباتي','متابعة الطلبات وحالاتها',()=>_orders(context,repo.watchBuyerOrders(uid),'طلباتي',false,repo)),
      _section(context,'🏪 طلبات البيع','قبول وتجهيز وشحن طلبات العملاء',()=>_orders(context,repo.watchSellerOrders(uid),'طلبات البيع',true,repo)),
      _section(context,'📊 تحليلات البائع','المشاهدات والرسائل والحفظ الفعلية',()=>_analytics(context)),
      _section(context,'⭐ التقييمات','تقييمات المنتجات والخدمات',()=>_reviews(context,repo)),
      _section(context,'🏷️ العروض','إدارة عروض المنتجات',()=>_offers(context,repo)),
      Card(child:ListTile(leading:const Icon(Icons.payments_outlined),title:const Text('الدفع والعمولة'),subtitle:const Text('الدفع الإلكتروني حالياً في وضع pending_gateway؛ لا يتم خصم أي مبلغ تلقائياً. يمكن للبائع متابعة إجمالي الطلبات من هنا.'),onTap:()=>_paymentInfo(context,repo,uid))),
      const Card(child:ListTile(leading:Icon(Icons.local_shipping_outlined),title:Text('التوصيل والشحن'),subtitle:Text('حالة الطلب: pending → confirmed → processing → shipped → delivered → cancelled.'))),
    ]));
  }
  Widget _section(BuildContext c,String title,String sub,VoidCallback tap)=>Card(child:ListTile(title:Text(title),subtitle:Text(sub),trailing:const Icon(Icons.chevron_right),onTap:tap));
  void _cart(BuildContext c,MarketplaceCommerceRepository repo,String uid)=>showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>StreamBuilder<List<Map<String,dynamic>>>(stream:repo.watchCart(uid),builder:(c,s){final items=s.data??[];return SizedBox(height:MediaQuery.of(c).size.height*.7,child:ListView(padding:const EdgeInsets.all(20),children:[const Text('السلة',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...items.map((x)=>ListTile(title:Text(x['name']?.toString()??x['productId']?.toString()??''),subtitle:Text('${x['quantity']??1} × ${x['unitPriceMinor']??0} ${x['currency']??''}'),trailing:IconButton(onPressed:()=>repo.removeFromCart(uid,x['productId']),icon:const Icon(Icons.delete_outline)))),const SizedBox(height:16),FilledButton.icon(onPressed:items.isEmpty?null:()async{String method='cash_on_delivery';final addressController=TextEditingController();final phoneController=TextEditingController();final ok=await showDialog<bool>(context:c,builder:(d)=>AlertDialog(title:const Text('إتمام الطلب'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:addressController,decoration:const InputDecoration(labelText:'عنوان التوصيل',hintText:'المدينة، المنطقة، العنوان')),const SizedBox(height:8),TextField(controller:phoneController,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم الهاتف')),const SizedBox(height:12),DropdownButtonFormField<String>(value:method,items:const [DropdownMenuItem(value:'cash_on_delivery',child:Text('الدفع عند الاستلام')),DropdownMenuItem(value:'pending_gateway',child:Text('دفع إلكتروني لاحقاً'))],onChanged:(v)=>method=v??method)]) ,actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('تأكيد'))]));if(ok==true){try{if(addressController.text.trim().isEmpty||phoneController.text.trim().isEmpty) throw StateError('أدخل عنوان التوصيل ورقم الهاتف');await repo.checkoutCart(uid:uid,paymentMethod:method,deliveryAddress:addressController.text,deliveryPhone:phoneController.text);if(c.mounted){Navigator.pop(c);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('تم إنشاء الطلبات')));}}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('تعذر إتمام الطلب: $e')));}}},icon:const Icon(Icons.check_circle_outline),label:const Text('إتمام الطلب'))]));}));
  void _orders(BuildContext c,Stream<List<Map<String,dynamic>>> stream,String title,bool seller,MarketplaceCommerceRepository repo)=>showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>StreamBuilder<List<Map<String,dynamic>>>(stream:stream,builder:(c,s)=>SizedBox(height:MediaQuery.of(c).size.height*.82,child:ListView(padding:const EdgeInsets.all(20),children:[Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...((s.data??[]).map((x)=>Card(child:ListTile(leading:(x['productImageUrl']?.toString()??'').isEmpty?const Icon(Icons.shopping_bag_outlined):Image.network(x['productImageUrl'],width:48,height:48,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.shopping_bag_outlined)),title:Text(x['productName']?.toString().isNotEmpty==true?x['productName']: 'طلب ${x['id']}'),subtitle:Text('${x['quantity']??1} × ${(x['totalMinor']??0)} ${x['currency']??''} • ${_statusLabel(x['status']?.toString()??'pending')}\n📍 ${x['deliveryAddress']?.toString()??'عنوان غير متوفر'}'),trailing:seller?PopupMenuButton<String>(onSelected:(v)=>repo.updateOrderStatus(x['id'],v),itemBuilder:(_)=>const [PopupMenuItem(value:'confirmed',child:Text('تأكيد')),PopupMenuItem(value:'processing',child:Text('تجهيز')),PopupMenuItem(value:'shipped',child:Text('شحن')),PopupMenuItem(value:'delivered',child:Text('تم التسليم')),PopupMenuItem(value:'cancelled',child:Text('إلغاء'))]):IconButton(onPressed:()=>_orderDetails(c,x),icon:const Icon(Icons.timeline_outlined)))))])])));  void _orderDetails(BuildContext c,Map<String,dynamic> x){final status=x['status']?.toString()??'pending';const steps=['pending','confirmed','processing','shipped','delivered'];final idx=steps.indexOf(status);showModalBottomSheet(context:c,builder:(_)=>ListView(padding:const EdgeInsets.all(24),children:[Text(x['productName']?.toString()??'تفاصيل الطلب',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),Text('📍 ${x['deliveryAddress']??'عنوان غير متوفر'}'),Text('📞 ${x['deliveryPhone']??'رقم غير متوفر'}'),const SizedBox(height:8),Text('⏱️ ${_etaLabel(x['estimatedDeliveryAt'])}'),const SizedBox(height:20),...steps.asMap().entries.map((e)=>ListTile(leading:CircleAvatar(child:Text('${e.key+1}')),title:Text(_statusLabel(e.value)),subtitle:Text(e.key<=idx?'تم الوصول لهذه المرحلة':'بانتظار المرحلة'),trailing:Icon(e.key<=idx?Icons.check_circle:Icons.radio_button_unchecked))),if(status=='shipped')const Card(child:ListTile(leading:Icon(Icons.schedule),title:Text('التوصيل متوقع بعد الشحن'),subtitle:Text('الوقت الدقيق يحتاج شركة شحن أو سائق مرتبط بالطلب.')))]));}
  void _paymentInfo(BuildContext c,MarketplaceCommerceRepository repo,String uid)=>showModalBottomSheet(context:c,builder:(_)=>FutureBuilder<Map<String,int>>(future:repo.sellerFinancialSummary(uid),builder:(c,s){final a=s.data??{};return ListView(padding:const EdgeInsets.all(24),children:[const Text('ملخص البائع',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:16),_stat('إجمالي الطلبات',a['orders']??0),_stat('إجمالي المبيعات',a['grossMinor']??0),_stat('عمولة AUREN',a['commissionMinor']??0),_stat('صافي البائع',a['netMinor']??0),const SizedBox(height:12),const Text('الأرقام هنا محاسبية داخلية فقط؛ لا تمثل أموالاً محصلة حتى يتم ربط بوابة دفع فعلية.')]);}));
  String _etaLabel(dynamic value){if(value is Timestamp){final d=value.toDate();return 'متوقع ${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';}return 'موعد التوصيل غير محدد';}
  String _statusLabel(String s){const m={'pending':'قيد الانتظار','confirmed':'تم التأكيد','processing':'قيد التجهيز','shipped':'تم الشحن','delivered':'تم التسليم','cancelled':'ملغي'};return m[s]??s;}
  void _analytics(BuildContext c){final uid=FirebaseAuth.instance.currentUser?.uid;if(uid==null)return;showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>FutureBuilder<Map<String,int>>(future:MarketplaceRepository().analytics(uid),builder:(c,s){if(!s.hasData)return const SizedBox(height:220,child:Center(child:CircularProgressIndicator()));final a=s.data!;return SizedBox(height:360,child:ListView(padding:const EdgeInsets.all(20),children:[const Text('تحليلات Marketplace',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:16),_stat('الإعلانات',a['products']??0),_stat('المشاهدات',a['views']??0),_stat('الرسائل',a['messages']??0),_stat('الحفظ',a['saves']??0)]));}));}
Widget _stat(String title,int value)=>Card(child:ListTile(title:Text(value.toString(),style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),subtitle:Text(title)));
  void _reviews(BuildContext c,MarketplaceCommerceRepository repo)=>showModalBottomSheet(context:c,builder:(_)=>StreamBuilder<List<Map<String,dynamic>>>(stream:repo.watchBuyerOrders(FirebaseAuth.instance.currentUser!.uid),builder:(c,s){final orders=s.data??[];return ListView(padding:const EdgeInsets.all(24),children:[const Text('التقييمات',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(orders.isEmpty)const Text('لا توجد طلبات بعد.') else ...orders.map((o)=>ListTile(leading:const Icon(Icons.star_outline),title:Text(o['productId']?.toString()??''),subtitle:Text('يمكن تقييم المنتج بعد الشراء')))]); }));
  void _offers(BuildContext c,MarketplaceCommerceRepository repo)=>showModalBottomSheet(context:c,builder:(_)=>const Padding(padding:EdgeInsets.all(24),child:Text('العروض أصبحت مدعومة في طبقة Marketplace.')));
}
