class CertificationCatalog {
  static const providers = <String>["Microsoft","Cisco","Google","AWS","Oracle","IBM","CompTIA","Adobe","PMI","ISC2","Linux Foundation","Red Hat","Unity","HubSpot","Salesforce","Autodesk","Meta","Intuit","AAO","ABET","ACM","IEEE","IET","Royal Society of Chemistry","American Chemical Society","ICF"];
  static const certifications = <Map<String, String>>[
    {'provider':'Microsoft','name':'Azure Fundamentals (AZ-900)','area':'Cloud Computing'},
    {'provider':'Microsoft','name':'Azure Administrator (AZ-104)','area':'Cloud Computing'},
    {'provider':'Microsoft','name':'Azure AI Fundamentals (AI-900)','area':'AI & Machine Learning'},
    {'provider':'Microsoft','name':'Azure Data Fundamentals (DP-900)','area':'Data Science'},
    {'provider':'Cisco','name':'CCNA','area':'Networking'},
    {'provider':'Cisco','name':'CyberOps Associate','area':'Cybersecurity'},
    {'provider':'Google','name':'Associate Cloud Engineer','area':'Cloud Computing'},
    {'provider':'Google','name':'Professional Data Engineer','area':'Data Science'},
    {'provider':'AWS','name':'Cloud Practitioner','area':'Cloud Computing'},
    {'provider':'AWS','name':'Solutions Architect – Associate','area':'Cloud Computing'},
    {'provider':'AWS','name':'Machine Learning – Specialty','area':'AI & Machine Learning'},
    {'provider':'Oracle','name':'Java Certification','area':'Software Engineering'},
    {'provider':'Oracle','name':'Database Certification','area':'Databases'},
    {'provider':'IBM','name':'Data Science Professional Certificate','area':'Data Science'},
    {'provider':'IBM','name':'AI Engineering Professional Certificate','area':'AI & Machine Learning'},
    {'provider':'CompTIA','name':'A+','area':'IT Support'},
    {'provider':'CompTIA','name':'Network+','area':'Networking'},
    {'provider':'CompTIA','name':'Security+','area':'Cybersecurity'},
    {'provider':'CompTIA','name':'Data+','area':'Data Science'},
    {'provider':'CompTIA','name':'Cloud+','area':'Cloud Computing'},
    {'provider':'Adobe','name':'Adobe Certified Professional','area':'Graphic Design'},
    {'provider':'PMI','name':'CAPM','area':'Project Management'},
    {'provider':'PMI','name':'PMP','area':'Project Management'},
    {'provider':'ISC2','name':'Certified in Cybersecurity','area':'Cybersecurity'},
    {'provider':'ISC2','name':'CISSP','area':'Cybersecurity'},
    {'provider':'Linux Foundation','name':'LFCS','area':'Linux & Systems'},
    {'provider':'Red Hat','name':'RHCSA','area':'Linux & Systems'},
    {'provider':'Unity','name':'Unity Certified User','area':'Game Development'},
    {'provider':'HubSpot','name':'HubSpot Academy Certifications','area':'Marketing & Sales'},
    {'provider':'Salesforce','name':'Administrator','area':'Business & CRM'},
    {'provider':'Autodesk','name':'Autodesk Certified User','area':'3D & Design'},
    {'provider':'Meta','name':'Meta Front-End Developer Certificate','area':'Web Development'},
    {'provider':'Intuit','name':'QuickBooks Certification','area':'Accounting & Finance'},
    {'provider':'AUREN Education Path','name':'Mathematics Professional Certificate','area':'Mathematics'},
    {'provider':'AUREN Education Path','name':'Physics Professional Certificate','area':'Physics'},
    {'provider':'AUREN Education Path','name':'Chemistry Professional Certificate','area':'Chemistry'},
    {'provider':'AUREN Education Path','name':'Biology Professional Certificate','area':'Biology'},
    {'provider':'AUREN Education Path','name':'Earth Science Professional Certificate','area':'Earth Science'},
    {'provider':'AUREN Education Path','name':'Astronomy Professional Certificate','area':'Astronomy'},
    {'provider':'AUREN Education Path','name':'Environmental Science Professional Certificate','area':'Environmental Science'},
    {'provider':'AUREN Education Path','name':'Computer Science Professional Certificate','area':'Computer Science'},
    {'provider':'AUREN Education Path','name':'Software Engineering Professional Certificate','area':'Software Engineering'},
    {'provider':'AUREN Education Path','name':'Web Development Professional Certificate','area':'Web Development'},
    {'provider':'AUREN Education Path','name':'Mobile Development Professional Certificate','area':'Mobile Development'},
    {'provider':'AUREN Education Path','name':'AI & Machine Learning Professional Certificate','area':'AI & Machine Learning'},
    {'provider':'AUREN Education Path','name':'Data Science Professional Certificate','area':'Data Science'},
    {'provider':'AUREN Education Path','name':'Cybersecurity Professional Certificate','area':'Cybersecurity'},
    {'provider':'AUREN Education Path','name':'Cloud Computing Professional Certificate','area':'Cloud Computing'},
    {'provider':'AUREN Education Path','name':'Networking Professional Certificate','area':'Networking'},
    {'provider':'AUREN Education Path','name':'Databases Professional Certificate','area':'Databases'},
    {'provider':'AUREN Education Path','name':'Robotics Professional Certificate','area':'Robotics'},
    {'provider':'AUREN Education Path','name':'IoT Professional Certificate','area':'IoT'},
    {'provider':'AUREN Education Path','name':'Game Development Professional Certificate','area':'Game Development'},
    {'provider':'AUREN Education Path','name':'UI/UX Design Professional Certificate','area':'UI/UX Design'},
    {'provider':'AUREN Education Path','name':'Graphic Design Professional Certificate','area':'Graphic Design'},
    {'provider':'AUREN Education Path','name':'Animation Professional Certificate','area':'Animation'},
    {'provider':'AUREN Education Path','name':'3D & VFX Professional Certificate','area':'3D & VFX'},
    {'provider':'AUREN Education Path','name':'Photography Professional Certificate','area':'Photography'},
    {'provider':'AUREN Education Path','name':'Film & Video Professional Certificate','area':'Film & Video'},
    {'provider':'AUREN Education Path','name':'Music Production Professional Certificate','area':'Music Production'},
    {'provider':'AUREN Education Path','name':'Audio Engineering Professional Certificate','area':'Audio Engineering'},
    {'provider':'AUREN Education Path','name':'Writing Professional Certificate','area':'Writing'},
    {'provider':'AUREN Education Path','name':'Journalism Professional Certificate','area':'Journalism'},
    {'provider':'AUREN Education Path','name':'Languages & Translation Professional Certificate','area':'Languages & Translation'},
    {'provider':'AUREN Education Path','name':'History Professional Certificate','area':'History'},
    {'provider':'AUREN Education Path','name':'Geography Professional Certificate','area':'Geography'},
    {'provider':'AUREN Education Path','name':'Philosophy Professional Certificate','area':'Philosophy'},
    {'provider':'AUREN Education Path','name':'Psychology Professional Certificate','area':'Psychology'},
    {'provider':'AUREN Education Path','name':'Sociology Professional Certificate','area':'Sociology'},
    {'provider':'AUREN Education Path','name':'Political Science Professional Certificate','area':'Political Science'},
    {'provider':'AUREN Education Path','name':'Economics Professional Certificate','area':'Economics'},
    {'provider':'AUREN Education Path','name':'Accounting & Finance Professional Certificate','area':'Accounting & Finance'},
    {'provider':'AUREN Education Path','name':'Banking Professional Certificate','area':'Banking'},
    {'provider':'AUREN Education Path','name':'Business Administration Professional Certificate','area':'Business Administration'},
    {'provider':'AUREN Education Path','name':'Entrepreneurship Professional Certificate','area':'Entrepreneurship'},
    {'provider':'AUREN Education Path','name':'Marketing & Sales Professional Certificate','area':'Marketing & Sales'},
    {'provider':'AUREN Education Path','name':'Project Management Professional Certificate','area':'Project Management'},
    {'provider':'AUREN Education Path','name':'Product Management Professional Certificate','area':'Product Management'},
    {'provider':'AUREN Education Path','name':'Human Resources Professional Certificate','area':'Human Resources'},
    {'provider':'AUREN Education Path','name':'Supply Chain Professional Certificate','area':'Supply Chain'},
    {'provider':'AUREN Education Path','name':'Procurement Professional Certificate','area':'Procurement'},
    {'provider':'AUREN Education Path','name':'Logistics Professional Certificate','area':'Logistics'},
    {'provider':'AUREN Education Path','name':'International Trade Professional Certificate','area':'International Trade'},
    {'provider':'AUREN Education Path','name':'Law Professional Certificate','area':'Law'},
    {'provider':'AUREN Education Path','name':'Public Policy Professional Certificate','area':'Public Policy'},
    {'provider':'AUREN Education Path','name':'Education Professional Certificate','area':'Education'},
    {'provider':'AUREN Education Path','name':'Teaching Professional Certificate','area':'Teaching'},
    {'provider':'AUREN Education Path','name':'Research Methods Professional Certificate','area':'Research Methods'},
    {'provider':'AUREN Education Path','name':'Medicine Professional Certificate','area':'Medicine'},
    {'provider':'AUREN Education Path','name':'Nursing Professional Certificate','area':'Nursing'},
    {'provider':'AUREN Education Path','name':'Pharmacy Professional Certificate','area':'Pharmacy'},
    {'provider':'AUREN Education Path','name':'Dentistry Professional Certificate','area':'Dentistry'},
    {'provider':'AUREN Education Path','name':'Public Health Professional Certificate','area':'Public Health'},
    {'provider':'AUREN Education Path','name':'Nutrition Professional Certificate','area':'Nutrition'},
    {'provider':'AUREN Education Path','name':'Sports Science Professional Certificate','area':'Sports Science'},
    {'provider':'AUREN Education Path','name':'Fitness Professional Certificate','area':'Fitness'},
    {'provider':'AUREN Education Path','name':'Agriculture Professional Certificate','area':'Agriculture'},
    {'provider':'AUREN Education Path','name':'Agronomy Professional Certificate','area':'Agronomy'},
    {'provider':'AUREN Education Path','name':'Horticulture Professional Certificate','area':'Horticulture'},
    {'provider':'AUREN Education Path','name':'Livestock Professional Certificate','area':'Livestock'},
    {'provider':'AUREN Education Path','name':'Veterinary Science Professional Certificate','area':'Veterinary Science'},
    {'provider':'AUREN Education Path','name':'Fisheries Professional Certificate','area':'Fisheries'},
    {'provider':'AUREN Education Path','name':'Forestry Professional Certificate','area':'Forestry'},
    {'provider':'AUREN Education Path','name':'Food Science Professional Certificate','area':'Food Science'},
    {'provider':'AUREN Education Path','name':'Civil Engineering Professional Certificate','area':'Civil Engineering'},
    {'provider':'AUREN Education Path','name':'Mechanical Engineering Professional Certificate','area':'Mechanical Engineering'},
    {'provider':'AUREN Education Path','name':'Electrical Engineering Professional Certificate','area':'Electrical Engineering'},
    {'provider':'AUREN Education Path','name':'Electronics Professional Certificate','area':'Electronics'},
    {'provider':'AUREN Education Path','name':'Chemical Engineering Professional Certificate','area':'Chemical Engineering'},
    {'provider':'AUREN Education Path','name':'Industrial Engineering Professional Certificate','area':'Industrial Engineering'},
    {'provider':'AUREN Education Path','name':'Architecture Professional Certificate','area':'Architecture'},
    {'provider':'AUREN Education Path','name':'Urban Planning Professional Certificate','area':'Urban Planning'},
    {'provider':'AUREN Education Path','name':'Renewable Energy Professional Certificate','area':'Renewable Energy'},
    {'provider':'AUREN Education Path','name':'Oil & Gas Professional Certificate','area':'Oil & Gas'},
    {'provider':'AUREN Education Path','name':'Mining Professional Certificate','area':'Mining'},
    {'provider':'AUREN Education Path','name':'Construction Professional Certificate','area':'Construction'},
    {'provider':'AUREN Education Path','name':'Automotive Professional Certificate','area':'Automotive'},
    {'provider':'AUREN Education Path','name':'Aviation Professional Certificate','area':'Aviation'},
    {'provider':'AUREN Education Path','name':'Maritime Professional Certificate','area':'Maritime'},
    {'provider':'AUREN Education Path','name':'Hospitality Professional Certificate','area':'Hospitality'},
    {'provider':'AUREN Education Path','name':'Tourism Professional Certificate','area':'Tourism'},
    {'provider':'AUREN Education Path','name':'Culinary Arts Professional Certificate','area':'Culinary Arts'},
    {'provider':'AUREN Education Path','name':'Fashion Professional Certificate','area':'Fashion'},
    {'provider':'AUREN Education Path','name':'Beauty Professional Certificate','area':'Beauty'},
    {'provider':'AUREN Education Path','name':'Crafts Professional Certificate','area':'Crafts'},
    {'provider':'AUREN Education Path','name':'Real Estate Professional Certificate','area':'Real Estate'},
    {'provider':'AUREN Education Path','name':'Social Work Professional Certificate','area':'Social Work'},
    {'provider':'AUREN Education Path','name':'Community Development Professional Certificate','area':'Community Development'},
    {'provider':'AUREN Education Path','name':'Leadership Professional Certificate','area':'Leadership'},
    {'provider':'AUREN Education Path','name':'Communication Professional Certificate','area':'Communication'},
    {'provider':'AUREN Education Path','name':'Personal Development Professional Certificate','area':'Personal Development'},
    {'provider':'AUREN Education Path','name':'Career Development Professional Certificate','area':'Career Development'},
    {'provider':'AUREN Education Path','name':'Financial Literacy Professional Certificate','area':'Financial Literacy'},
    {'provider':'AUREN Education Path','name':'Digital Literacy Professional Certificate','area':'Digital Literacy'},
    {'provider':'AUREN Education Path','name':'Vocational Training Professional Certificate','area':'Vocational Training'},
  ];
  static const scientificAreas = <String>[
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Earth Science',
    'Astronomy',
    'Environmental Science',
    'Computer Science',
    'Software Engineering',
    'Web Development',
    'Mobile Development',
    'AI & Machine Learning',
    'Data Science',
    'Cybersecurity',
    'Cloud Computing',
    'Networking',
    'Databases',
    'Robotics',
    'IoT',
    'Game Development',
    'UI/UX Design',
    'Graphic Design',
    'Animation',
    '3D & VFX',
    'Photography',
    'Film & Video',
    'Music Production',
    'Audio Engineering',
    'Writing',
    'Journalism',
    'Languages & Translation',
    'History',
    'Geography',
    'Philosophy',
    'Psychology',
    'Sociology',
    'Political Science',
    'Economics',
    'Accounting & Finance',
    'Banking',
    'Business Administration',
    'Entrepreneurship',
    'Marketing & Sales',
    'Project Management',
    'Product Management',
    'Human Resources',
    'Supply Chain',
    'Procurement',
    'Logistics',
    'International Trade',
    'Law',
    'Public Policy',
    'Education',
    'Teaching',
    'Research Methods',
    'Medicine',
    'Nursing',
    'Pharmacy',
    'Dentistry',
    'Public Health',
    'Nutrition',
    'Sports Science',
    'Fitness',
    'Agriculture',
    'Agronomy',
    'Horticulture',
    'Livestock',
    'Veterinary Science',
    'Fisheries',
    'Forestry',
    'Food Science',
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Electronics',
    'Chemical Engineering',
    'Industrial Engineering',
    'Architecture',
    'Urban Planning',
    'Renewable Energy',
    'Oil & Gas',
    'Mining',
    'Construction',
    'Automotive',
    'Aviation',
    'Maritime',
    'Hospitality',
    'Tourism',
    'Culinary Arts',
    'Fashion',
    'Beauty',
    'Crafts',
    'Real Estate',
    'Social Work',
    'Community Development',
    'Leadership',
    'Communication',
    'Personal Development',
    'Career Development',
    'Financial Literacy',
    'Digital Literacy',
    'Vocational Training',
  ];
}
