import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../services/travel/travel_repository.dart';
import '../../../core/models/travel.dart';
import '../../messenger/presentation/messenger_screen.dart';

class AurenAURENTravelScreen extends StatefulWidget{const AurenAURENTravelScreen({super.key});@override State<AurenAURENTravelScreen> createState()=>_TravelState();}
class _TravelState extends State<AurenAURENTravelScreen>{final repo=TravelRepository();String query='';String? category;
@override Widget build(BuildContext context){final uid=FirebaseAuth.instance.currentUser?.uid;return Scaffold(appBar:AppBar(title:const Text('AUREN Travel'),actions:[IconButton(icon:const Icon(Icons.auto_awesome),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const MessengerScreen(initialPrompt:'خطط لي رحلة كاملة تشمل الميزانية والأماكن والإقامة والتنقل.'))))]),body:StreamBuilder<List<AurenPlace>>(stream:repo.watchPlaces(),builder:(context,s){if(s.hasError)return Center(child:Text('تعذر تحميل السفر: '+s.error.toString()));if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final all=s.data??const <AurenPlace>[];final cats=all.map((e)=>e.category).toSet().toList()..sort();final q=query.toLowerCase();final places=all.where((p)=>(q.isEmpty||(p.name+' '+p.city+' '+p.country+' '+p.description).toLowerCase().contains(q))&&(category==null||p.category==category)).toList();return ListView(padding:const EdgeInsets.all(16),children:[const ListTile(contentPadding:EdgeInsets.zero,leading:Icon(Icons.explore,size:34),title:Text('Discover the world',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),subtitle:Text('وجهات، إقامة، ثقافة، وتنقل في مكان واحد.')),TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث عن مكان أو مدينة'),onChanged:(v)=>setState(()=>query=v)),const SizedBox(height:8),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[null,...cats].map((c)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(c??'All'),selected:category==c,onSelected:(_)=>setState(()=>category=c))).toList()))),const SizedBox(height:12),
        if(uid!=null) ...[
          _trips(context, uid),
          const SizedBox(height:12),
        ],
        ...places.map((p)=>_place(context,p,uid))]);});}
Widget _trips(BuildContext context,String uid)=>StreamBuilder<List<AurenTrip>>(stream:repo.watchMyTrips(uid),builder:(context,s){final trips=s.data??const <AurenTrip>[];return Card(child:ExpansionTile(leading:const Icon(Icons.luggage_outlined),title:const Text('My Trips'),subtitle:Text(trips.isEmpty?'أنشئ أول رحلة من AUREN AI.':'${trips.length} رحلة محفوظة'),children:[if(trips.isEmpty)const Padding(padding:EdgeInsets.all(16),child:Text('استخدم AUREN AI لإنشاء خطة رحلة، ثم احفظها هنا.')),...trips.map((t)=>ListTile(title:Text(t.title),subtitle:Text(t.destination),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{await repo.deleteTrip(uid,t.id);}),onTap:()=>showDialog(context:context,builder:(_)=>AlertDialog(title:Text(t.title),content:Text('Destination: ${t.destination}\nPlaces: ${t.placeIds.length}'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]))))]));});
Widget _place(BuildContext context,AurenPlace p,String? uid)=>Card(child:ListTile(leading:p.imageUrl.isEmpty?const CircleAvatar(child:Icon(Icons.place)):CircleAvatar(backgroundImage:NetworkImage(p.imageUrl)),title:Text(p.name),subtitle:Text(p.city+', '+p.country+'\n'+p.description),isThreeLine:true,trailing:uid==null?null:StreamBuilder<Set<String>>(stream:repo.watchSavedIds(uid),builder:(context,s)=>IconButton(icon:Icon((s.data??{}).contains(p.id)?Icons.bookmark:Icons.bookmark_border),onPressed:()=>repo.toggleSaved(uid,p.id,!((s.data??{}).contains(p.id))))),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>MessengerScreen(initialPrompt:'اعمل لي دليل زيارة لـ'+p.name+' يشمل أفضل وقت والميزانية والأماكن المهمة.'))));}