/// Specialized AI capability catalog for every AUREN Talent category.
///
/// These are talent-development tools. Employment, business operations,
/// agriculture sectors and skilled-service work remain outside Talent.
class AurenTalentSpecializedCapability {
  final String id;
  final String name;
  final String prompt;
  const AurenTalentSpecializedCapability({
    required this.id,
    required this.name,
    required this.prompt,
  });
}

class AurenTalentSpecializedCatalog {
  static const byCategory = <String, List<AurenTalentSpecializedCapability>>{
    'sports': [
      AurenTalentSpecializedCapability(id:'sports_performance_lab',name:'Performance Lab',prompt:'حلّل بيانات أدائي الرياضي التي أقدمها وحدد نقاط القوة ومجالات التطوير والخطوة التالية بدون تشخيص طبي.'),
      AurenTalentSpecializedCapability(id:'sports_training_plan',name:'Training Plan',prompt:'أنشئ لي خطة تدريب رياضية تدريجية حسب رياضتي ومستواي وهدفي ووقتي، مع مؤشرات متابعة واضحة.'),
      AurenTalentSpecializedCapability(id:'sports_video_review',name:'Video Review',prompt:'راجع فيديو أدائي الرياضي عند إرفاقه وحدد الملاحظات الفنية الظاهرة وما يمكن تحسينه دون ادعاء قياسات غير متاحة.'),
      AurenTalentSpecializedCapability(id:'sports_highlights',name:'Highlight Builder',prompt:'حوّل أفضل لقطات وإنجازات أدائي الرياضي إلى تصور Highlight مرتب ومناسب لملف الموهبة.'),
      AurenTalentSpecializedCapability(id:'sports_tryout',name:'Tryout Coach',prompt:'جهزني لاختبار أداء رياضي عبر قائمة تحضير ومهام ونقاط أركز عليها قبل التجربة.'),
      AurenTalentSpecializedCapability(id:'sports_progress',name:'Progress Tracker',prompt:'حوّل سجلات أدائي الرياضي إلى قصة تطور تقارنني بنفسي عبر الزمن وتحدد الخطوة التالية.'),
      AurenTalentSpecializedCapability(id:'sports_highlight_video',name:'Highlight Video Studio',prompt:'حوّل لقطات أدائي الرياضي إلى تصور لفيديو Highlight مرتب مع افتتاحية ونهاية وعناوين وإيقاع مناسب.'),
      AurenTalentSpecializedCapability(id:'sports_profile_visual',name:'Athlete Visual Pack',prompt:'أنشئ تصورًا بصريًا لصورتي الرياضية يشمل غلافًا وبطاقة لاعب ومواد عرض لملف Talent.'),
      AurenTalentSpecializedCapability(id:'sports_training_visual',name:'Training Visualizer',prompt:'حوّل خطة تدريبي إلى لوحات أو فيديو توضيحي بصري يسهل متابعة التمارين والمراحل.'),
      AurenTalentSpecializedCapability(id:'sports_story',name:'Athlete Story Studio',prompt:'حوّل مسيرتي الرياضية وإنجازاتي والأدلة التي أقدمها إلى قصة مرئية قابلة للمشاركة.'),
    ],
    'music': [
      AurenTalentSpecializedCapability(id:'music_song_lab',name:'Song Creation Lab',prompt:'ساعدني في صناعة أغنية من الفكرة إلى الكلمات والبناء واللحن والـKey والـBPM والترتيب والتجهيز للتسجيل.'),
      AurenTalentSpecializedCapability(id:'music_demo_lab',name:'Demo Lab',prompt:'ساعدني في تخطيط Demo لأغنيتي: التسجيل، الطبقات، الترتيب، الملاحظات والنسخ التي أحتاج الاحتفاظ بها.'),
      AurenTalentSpecializedCapability(id:'music_vocal_coach',name:'Vocal Coach',prompt:'ابنِ لي خطة تدريب صوتي مناسبة لمستواي، وإذا قدمت تسجيلًا افصل بين الملاحظات المسموعة والقياسات التي تحتاج أداة تحليل.'),
      AurenTalentSpecializedCapability(id:'music_arrangement',name:'Arrangement Lab',prompt:'حوّل فكرة أغنيتي إلى Arrangement واضح من Intro وVerse وChorus وBridge وOutro مع اقتراحات مناسبة للنوع الموسيقي.'),
      AurenTalentSpecializedCapability(id:'music_release',name:'Release Builder',prompt:'حوّل أغنيتي الجاهزة إلى خطة إصدار تشمل الهوية والوصف والمحتوى والتجهيز والـcredits والمتابعة.'),
      AurenTalentSpecializedCapability(id:'music_collab',name:'Music Collaboration',prompt:'حدد الأدوار الموسيقية التي أحتاجها لإكمال الأغنية واقترح نوع الموهبة المكملة لي للتعاون.'),
      AurenTalentSpecializedCapability(id:'music_song_generator',name:'AI Song Generator',prompt:'حوّل فكرة أو كلمات أو وصفًا موسيقيًا إلى مواصفات جاهزة لطلب توليد أغنية، مع النوع والمزاج والآلات وBPM والـKey.'),
      AurenTalentSpecializedCapability(id:'music_cover_art',name:'Cover Art Studio',prompt:'أنشئ تصورًا لغلاف الأغنية من اسمها وهويتها وكلماتها وصورة مرجعية إن قدمتها.'),
      AurenTalentSpecializedCapability(id:'music_video',name:'Music Video Studio',prompt:'حوّل الأغنية وصورتها أو صورًا مرجعية إلى تصور Music Video بمشاهد وانتقالات وحركة متزامنة مع الموسيقى.'),
      AurenTalentSpecializedCapability(id:'music_image_to_video',name:'Image-to-Video Music',prompt:'حوّل صورة الفنان أو الغلاف إلى مشهد فيديو موسيقي متحرك مع وصف الحركة والجو والإضاءة.'),
      AurenTalentSpecializedCapability(id:'music_lyric_video',name:'Lyric Video Studio',prompt:'أنشئ تصور فيديو كلمات متزامن مع بنية الأغنية وهوية الغلاف.'),
      AurenTalentSpecializedCapability(id:'music_visualizer',name:'Audio Visualizer',prompt:'أنشئ تصور Visualizer يتفاعل بصريًا مع الإيقاع والطاقة الموسيقية.'),
      AurenTalentSpecializedCapability(id:'music_promo_video',name:'Artist Promo Video',prompt:'حوّل صورة الفنان وبيانات الأغنية إلى فيديو ترويجي قصير مناسب للنشر.'),
      AurenTalentSpecializedCapability(id:'music_social_cuts',name:'Music Social Clips',prompt:'قسّم الأغنية إلى أفكار مقاطع قصيرة متعددة مع Hooks وبدايات ونهايات مناسبة.'),
      AurenTalentSpecializedCapability(id:'music_stem_plan',name:'Stem & Production Plan',prompt:'خطط لفصل وتنظيم الصوتيات إلى Vocal وInstrumental وDrums وغيرها عندما تتوفر الملفات المناسبة.'),
      AurenTalentSpecializedCapability(id:'music_storyboard',name:'Music Video Storyboard',prompt:'أنشئ Storyboard مشهدًا بمشهد لفيديو الأغنية قبل الإنتاج.'),
      AurenTalentSpecializedCapability(id:'music_release_media',name:'Release Media Pack',prompt:'جهز حزمة إصدار تشمل الغلاف والـlyric video والـvisualizer والمقاطع القصيرة والوصف.'),
      AurenTalentSpecializedCapability(id:'music_creator_suite',name:'Music Creator Suite',prompt:'نسّق مشروع الأغنية من الفكرة والتسجيل والتحليل إلى الغلاف والفيديو ومواد الإصدار في مسار واحد.'),
    ],
    'arts_design': [
      AurenTalentSpecializedCapability(id:'art_critique',name:'Creative Critique',prompt:'راجع العمل الفني أو التصميم الذي أقدمه وحدد نقاط القوة والتكوين والوضوح ومجالات التطوير بشكل عملي.'),
      AurenTalentSpecializedCapability(id:'art_idea_lab',name:'Idea Lab',prompt:'طوّر فكرتي الفنية إلى مفهوم واضح، أسلوب بصري، مراجع إبداعية وخطوات تنفيذ.'),
      AurenTalentSpecializedCapability(id:'design_portfolio',name:'Design Portfolio',prompt:'رتب أفضل أعمالي في Portfolio تصميم يوضح المهارات والمشاريع ودوري في كل مشروع.'),
      AurenTalentSpecializedCapability(id:'visual_style',name:'Style Builder',prompt:'استخرج أسلوبي البصري من الأعمال التي أقدمها واقترح طريقة متماسكة لتطوير هويتي الفنية.'),
      AurenTalentSpecializedCapability(id:'art_challenge',name:'Creative Challenge',prompt:'أنشئ لي تحديًا فنيًا عمليًا مناسبًا لمستواي يطور مهارة محددة وينتج عملًا جديدًا.'),
      AurenTalentSpecializedCapability(id:'art_showcase',name:'Art Showcase',prompt:'حوّل أفضل أعمالي الفنية إلى Showcase قصير ومقنع لملف Talent.'),
      AurenTalentSpecializedCapability(id:'art_image_creator',name:'Visual Creation Studio',prompt:'حوّل فكرتي الفنية إلى Brief جاهز لتوليد صور أو أعمال بصرية مع أسلوب وتكوين وإضاءة.'),
      AurenTalentSpecializedCapability(id:'art_motion_video',name:'Art Motion Studio',prompt:'حوّل العمل الفني الثابت إلى تصور فيديو متحرك يحافظ على هويته البصرية.'),
      AurenTalentSpecializedCapability(id:'art_process_video',name:'Process Video Maker',prompt:'حوّل مراحل تنفيذ العمل الفني إلى Storyboard لفيديو Process جذاب.'),
      AurenTalentSpecializedCapability(id:'art_exhibition_pack',name:'Exhibition Media Pack',prompt:'أنشئ حزمة عرض تشمل الغلاف والبطاقات والوصف وفيديو تقديمي للأعمال.'),
    ],
    'film_acting': [
      AurenTalentSpecializedCapability(id:'acting_coach',name:'Acting Coach',prompt:'أنشئ لي تمرين تمثيل عملي لتطوير التعبير والحضور وفهم الشخصية حسب مستواي.'),
      AurenTalentSpecializedCapability(id:'audition_prep',name:'Audition Prep',prompt:'جهزني لاختبار أداء تمثيلي عبر تحليل المشهد وقائمة تحضير وأسئلة وتمارين قبل التسجيل.'),
      AurenTalentSpecializedCapability(id:'scene_lab',name:'Scene Lab',prompt:'طوّر فكرة مشهد إلى شخصيات وصراع وبنية وحوار واتجاه إخراجي مناسب.'),
      AurenTalentSpecializedCapability(id:'showreel_builder',name:'Showreel Builder',prompt:'رتب أفضل أعمالي التمثيلية في Showreel يبرز تنوع الأداء وأقوى اللحظات.'),
      AurenTalentSpecializedCapability(id:'film_portfolio',name:'Film Portfolio',prompt:'أنشئ Portfolio سينمائي من أعمالي وأدواري واعتماداتي وأدلة أدائي بدون اختلاق معلومات.'),
      AurenTalentSpecializedCapability(id:'performance_review',name:'Performance Review',prompt:'راجع أداء تمثيلي مرفق وحدد الملاحظات الظاهرة ونقاط القوة ومجالات التحسين دون ادعاء قياسات غير متاحة.'),
      AurenTalentSpecializedCapability(id:'film_scene_creator',name:'Scene Creation Studio',prompt:'طوّر فكرة المشهد إلى تصور بصري وسيناريو ولقطات مقترحة.'),
      AurenTalentSpecializedCapability(id:'film_poster',name:'Film Poster Studio',prompt:'أنشئ تصورًا لبوستر العمل من القصة والشخصيات والصورة المرجعية.'),
      AurenTalentSpecializedCapability(id:'film_reel_video',name:'Showreel Video Studio',prompt:'رتب اللقطات التي أقدمها إلى تصور Showreel بإيقاع وانتقالات وعناوين.'),
      AurenTalentSpecializedCapability(id:'film_storyboard',name:'Storyboard Studio',prompt:'حوّل السيناريو إلى Storyboard مشهدًا بمشهد مع زوايا وتصوير مقترحة.'),
    ],
    'photography': [
      AurenTalentSpecializedCapability(id:'photo_critique',name:'Photo Critique',prompt:'راجع الصورة التي أقدمها من ناحية التكوين والإضاءة والتركيز والقصة البصرية واقترح تحسينات عملية.'),
      AurenTalentSpecializedCapability(id:'photo_project',name:'Photo Project Lab',prompt:'حوّل فكرة تصوير إلى مشروع متكامل بموضوع وقائمة لقطات وأسلوب بصري وخطة تنفيذ.'),
      AurenTalentSpecializedCapability(id:'photo_story',name:'Photo Story',prompt:'رتب مجموعة صوري في قصة بصرية متماسكة مع عنوان وتسلسل ووصف.'),
      AurenTalentSpecializedCapability(id:'photo_portfolio',name:'Photo Portfolio',prompt:'ابنِ Portfolio تصوير يبرز أفضل أعمالي وتخصصي وتطوري.'),
      AurenTalentSpecializedCapability(id:'photo_challenge',name:'Photo Challenge',prompt:'أنشئ لي تحديًا تصويريًا يطور مهارة محددة وينتج سلسلة صور قابلة للعرض.'),
      AurenTalentSpecializedCapability(id:'photo_style',name:'Visual Style',prompt:'حلل نمط أعمالي التصويرية واقترح طريقة لتطوير هوية بصرية مميزة ومتسقة.'),
      AurenTalentSpecializedCapability(id:'photo_visual_creator',name:'Photo Concept Studio',prompt:'حوّل فكرة التصوير إلى Concepts بصرية واضحة مع تكوين وإضاءة وموقع ولقطات.'),
      AurenTalentSpecializedCapability(id:'photo_to_video',name:'Photo-to-Video Studio',prompt:'حوّل صورة أو سلسلة صور إلى تصور فيديو قصير بحركة وانتقالات.'),
      AurenTalentSpecializedCapability(id:'photo_story_video',name:'Photo Story Video',prompt:'حوّل مجموعة الصور إلى فيديو قصة متسلسل مع نصوص وعناوين.'),
      AurenTalentSpecializedCapability(id:'photo_promo_pack',name:'Photography Media Pack',prompt:'جهز غلافًا وفيديو قصيرًا ومواد عرض لأفضل مشروع تصوير.'),
    ],
    'technology': [
      AurenTalentSpecializedCapability(id:'tech_project_lab',name:'Project Lab',prompt:'حوّل فكرة تقنية إلى مشروع عملي بمشكلة وحل وميزات ومراحل تنفيذ واختبار.'),
      AurenTalentSpecializedCapability(id:'tech_skill_plan',name:'Coding Skill Plan',prompt:'أنشئ خطة تطوير برمجة عملية حسب مستواي والهدف والمشاريع التي أريد بناءها.'),
      AurenTalentSpecializedCapability(id:'tech_code_review',name:'Code Review',prompt:'راجع الكود الذي أقدمه وحدد الأخطاء والمخاطر والتحسينات بشكل واضح، ولا تفترض كودًا غير موجود.'),
      AurenTalentSpecializedCapability(id:'tech_portfolio',name:'Tech Portfolio',prompt:'حوّل مشاريعي البرمجية إلى Portfolio يوضح المشكلة والحل ودوري والنتائج والتقنيات.'),
      AurenTalentSpecializedCapability(id:'tech_build_challenge',name:'Build Challenge',prompt:'أعطني تحديًا برمجيًا عمليًا يناسب مستواي ويجبرني على بناء شيء حقيقي.'),
      AurenTalentSpecializedCapability(id:'tech_showcase',name:'Project Showcase',prompt:'أنشئ صفحة عرض مختصرة لمشروع تقني تبرز القيمة والميزات والدليل على التنفيذ.'),
      AurenTalentSpecializedCapability(id:'tech_demo_video',name:'Project Demo Video',prompt:'حوّل مشروعك التقني إلى سيناريو Demo Video يشرح المشكلة والحل والميزات.'),
      AurenTalentSpecializedCapability(id:'tech_visual_creator',name:'Tech Visual Studio',prompt:'أنشئ تصورًا بصريًا لواجهة أو معمارية أو تجربة المشروع.'),
      AurenTalentSpecializedCapability(id:'tech_explainer_video',name:'Tech Explainer Studio',prompt:'حوّل فكرة تقنية إلى Storyboard لفيديو Explainer مبسط.'),
      AurenTalentSpecializedCapability(id:'tech_showcase_pack',name:'Tech Showcase Pack',prompt:'جهز صور العرض والفيديو والنصوص المختصرة لعرض المشروع.'),
    ],
    'ai_innovation': [
      AurenTalentSpecializedCapability(id:'innovation_lab',name:'Innovation Lab',prompt:'طوّر فكرتي الابتكارية إلى مشكلة وحل وتجربة أولية ومؤشرات نجاح.'),
      AurenTalentSpecializedCapability(id:'ai_prototype',name:'AI Prototype',prompt:'حوّل فكرتي إلى تصور Prototype للذكاء الاصطناعي مع المدخلات والمخرجات والمخاطر.'),
      AurenTalentSpecializedCapability(id:'idea_validator',name:'Idea Validator',prompt:'اختبر فكرتي منطقيًا وحدد الفرضيات والمخاطر والتجارب التي يمكن تنفيذها قبل البناء.'),
      AurenTalentSpecializedCapability(id:'innovation_portfolio',name:'Innovation Portfolio',prompt:'رتب مشاريعي وأفكاري وتجارب النماذج الأولية في Portfolio ابتكار واضح.'),
      AurenTalentSpecializedCapability(id:'pitch_builder',name:'Innovation Pitch',prompt:'حوّل فكرتي إلى عرض Pitch مختصر يشرح المشكلة والحل والميزة والدليل والخطوة التالية.'),
      AurenTalentSpecializedCapability(id:'experiment_plan',name:'Experiment Plan',prompt:'أنشئ تجربة عملية لاختبار فرضية ابتكارية مع نتيجة متوقعة ومعيار نجاح واضح.'),
      AurenTalentSpecializedCapability(id:'innovation_visual',name:'Innovation Visual Studio',prompt:'حوّل فكرة الابتكار إلى تصور بصري Prototype أو Diagram أو مشهد استخدام.'),
      AurenTalentSpecializedCapability(id:'innovation_demo_video',name:'Prototype Demo Video',prompt:'أنشئ سيناريو فيديو يوضح المشكلة والنموذج الأولي وطريقة الاستخدام.'),
      AurenTalentSpecializedCapability(id:'innovation_explainer',name:'Innovation Explainer',prompt:'حوّل الابتكار إلى فيديو شرح قصير واضح للجمهور.'),
      AurenTalentSpecializedCapability(id:'innovation_showcase',name:'Innovation Showcase Pack',prompt:'جهز صورًا وفيديو ونص عرض متكامل لمشروع الابتكار.'),
    ],
    'writing': [
      AurenTalentSpecializedCapability(id:'writing_lab',name:'Writing Lab',prompt:'طوّر نصي أو فكرتي الكتابية مع الحفاظ على صوتي وأسلوب الكتابة، وحدد التحسينات بوضوح.'),
      AurenTalentSpecializedCapability(id:'story_builder',name:'Story Builder',prompt:'حوّل فكرتي إلى قصة بشخصيات وصراع وبنية ونهاية مناسبة للنوع الذي أختاره.'),
      AurenTalentSpecializedCapability(id:'writing_review',name:'Writing Review',prompt:'راجع النص الذي أقدمه من ناحية البناء والوضوح والأسلوب والإيقاع واللغة، مع اقتراحات عملية.'),
      AurenTalentSpecializedCapability(id:'author_portfolio',name:'Writer Portfolio',prompt:'أنشئ Portfolio للكاتب من أفضل الأعمال والأنواع والإنجازات والروابط.'),
      AurenTalentSpecializedCapability(id:'writing_challenge',name:'Writing Challenge',prompt:'أنشئ لي تحديًا كتابيًا يطور مهارة محددة وينتج نصًا جديدًا قابلًا للعرض.'),
      AurenTalentSpecializedCapability(id:'publishing_prep',name:'Publishing Prep',prompt:'جهز عملي الكتابي للنشر عبر مراجعة البنية والوصف والعنوان والملف التعريفي دون اختلاق بيانات.'),
      AurenTalentSpecializedCapability(id:'writing_cover',name:'Book Cover Concept',prompt:'حوّل فكرة الكتاب أو القصة إلى تصور غلاف بصري مناسب للهوية.'),
      AurenTalentSpecializedCapability(id:'writing_visual_story',name:'Visual Story Studio',prompt:'حوّل نصًا أو قصة إلى تصور مشاهد وصور وفيديو قصير دون تغيير صوت الكاتب.'),
      AurenTalentSpecializedCapability(id:'writing_book_trailer',name:'Book Trailer Studio',prompt:'أنشئ Storyboard لفيديو تشويقي للكتاب أو القصة.'),
      AurenTalentSpecializedCapability(id:'writing_media_pack',name:'Author Media Pack',prompt:'جهز غلافًا ومواد مرئية وفيديو تعريفي للعمل والكاتب.'),
    ],
    'creator': [
      AurenTalentSpecializedCapability(id:'content_lab',name:'Content Lab',prompt:'حوّل فكرتي إلى خطة محتوى عملية تشمل الفكرة والـHook والسيناريو والتصوير والنشر.'),
      AurenTalentSpecializedCapability(id:'script_builder',name:'Script Builder',prompt:'اكتب مخطط Script لمحتوى قصير أو طويل مع Hook وتسلسل واضح وCTA مناسب.'),
      AurenTalentSpecializedCapability(id:'creator_brand',name:'Creator Brand',prompt:'ابنِ هوية Creator واضحة تشمل المجال والجمهور والرسالة ونمط المحتوى.'),
      AurenTalentSpecializedCapability(id:'content_series',name:'Series Builder',prompt:'حوّل فكرة محتوى إلى سلسلة حلقات مترابطة مع أفكار لكل حلقة.'),
      AurenTalentSpecializedCapability(id:'creator_portfolio',name:'Creator Portfolio',prompt:'رتب أفضل محتواي في Creator Portfolio يوضح التخصص وأفضل الأعمال والإنجازات.'),
      AurenTalentSpecializedCapability(id:'creator_challenge',name:'Creator Challenge',prompt:'أنشئ تحديًا لصناعة المحتوى لمدة محددة يطور مهارة ويقيس التقدم.'),
      AurenTalentSpecializedCapability(id:'creator_image_studio',name:'Creator Image Studio',prompt:'أنشئ أفكارًا جاهزة للصور والـthumbnails والهوية البصرية للمحتوى.'),
      AurenTalentSpecializedCapability(id:'creator_video_studio',name:'Creator Video Studio',prompt:'حوّل فكرة المحتوى إلى فيديو من Hook وScript ومشاهد وانتقالات.'),
      AurenTalentSpecializedCapability(id:'creator_thumbnail',name:'Thumbnail Studio',prompt:'أنشئ مفهوم Thumbnail واضح يركز على الفكرة والعنوان والعنصر البصري الرئيسي.'),
      AurenTalentSpecializedCapability(id:'creator_content_pack',name:'Creator Media Pack',prompt:'جهز حزمة منشور تشمل الصورة والفيديو القصير والوصف والعنوان والنسخ المختلفة.'),
    ],
    'science_academic': [
      AurenTalentSpecializedCapability(id:'research_lab',name:'Research Lab',prompt:'حوّل فكرتي إلى سؤال بحث وفرضية ومنهجية ومخرجات قابلة للقياس مع مراعاة حدود البيانات.'),
      AurenTalentSpecializedCapability(id:'study_plan',name:'Study Plan',prompt:'أنشئ خطة دراسة عملية حسب مستواي وهدفي ووقتي مع مهام ومراجعة دورية.'),
      AurenTalentSpecializedCapability(id:'research_review',name:'Research Review',prompt:'راجع المادة العلمية التي أقدمها وحدد نقاط القوة والفجوات والأسئلة التي تحتاج مصادر أو تحقق.'),
      AurenTalentSpecializedCapability(id:'academic_portfolio',name:'Academic Portfolio',prompt:'أنشئ Academic Portfolio من المشاريع والأبحاث والإنجازات والأدلة التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'science_project',name:'Science Project',prompt:'صمم لي مشروعًا علميًا عمليًا مناسبًا لمستواي مع سؤال وتجربة ونتائج متوقعة.'),
      AurenTalentSpecializedCapability(id:'research_showcase',name:'Research Showcase',prompt:'حوّل مشروعًا أو بحثًا إلى عرض مبسط يوضح المشكلة والمنهجية والنتائج والحدود.'),
      AurenTalentSpecializedCapability(id:'science_visualizer',name:'Science Visualizer',prompt:'حوّل مفهومًا علميًا أو نتيجة بحث إلى رسم أو تصور بصري واضح.'),
      AurenTalentSpecializedCapability(id:'science_explainer_video',name:'Science Explainer Video',prompt:'أنشئ Storyboard لفيديو يشرح المفهوم العلمي بلغة مناسبة للجمهور.'),
      AurenTalentSpecializedCapability(id:'science_poster',name:'Academic Poster Studio',prompt:'حوّل البحث أو المشروع إلى تصور Poster أكاديمي منظم.'),
      AurenTalentSpecializedCapability(id:'science_showcase_video',name:'Research Showcase Video',prompt:'أنشئ سيناريو فيديو مختصر لعرض المشكلة والمنهجية والنتائج والحدود.'),
    ],
    'gaming_esports': [
      AurenTalentSpecializedCapability(id:'gaming_review',name:'Gameplay Review',prompt:'راجع بيانات أو فيديو لعب أقدمه وحدد القرارات ونقاط القوة ومجالات التحسين دون ادعاء بيانات غير موجودة.'),
      AurenTalentSpecializedCapability(id:'gaming_training',name:'Training Plan',prompt:'أنشئ خطة تدريب للألعاب التنافسية حسب اللعبة ومستواي والمهارة التي أريد تطويرها.'),
      AurenTalentSpecializedCapability(id:'gaming_strategy',name:'Strategy Lab',prompt:'حلل أسلوبي في اللعبة واقترح استراتيجيات وتمارين لتحسين اتخاذ القرار.'),
      AurenTalentSpecializedCapability(id:'esports_profile',name:'Esports Profile',prompt:'أنشئ ملف Esports يوضح اللعبة والدور والإحصائيات والإنجازات والأدلة التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'gaming_highlights',name:'Gaming Highlights',prompt:'رتب أفضل لحظات لعبي إلى تصور Highlight مناسب لملف Gaming Talent.'),
      AurenTalentSpecializedCapability(id:'gaming_challenge',name:'Skill Challenge',prompt:'أنشئ تحديًا تدريبيًا داخل اللعبة يطور مهارة محددة ويمكن قياس تقدمه.'),
      AurenTalentSpecializedCapability(id:'gaming_highlight_video',name:'Gaming Highlight Video',prompt:'حوّل لقطات اللعب إلى تصور Highlight سريع مع لحظات رئيسية وعناوين.'),
      AurenTalentSpecializedCapability(id:'gaming_thumbnail',name:'Gaming Thumbnail Studio',prompt:'أنشئ مفهوم Thumbnail للعبة أو الإنجاز أو التحدي.'),
      AurenTalentSpecializedCapability(id:'gaming_stream_pack',name:'Streamer Media Pack',prompt:'جهز هوية مرئية للبث تشمل الغلاف والمقدمة ومشاهد الانتقال.'),
      AurenTalentSpecializedCapability(id:'gaming_recap_video',name:'Match Recap Studio',prompt:'حوّل بيانات المباراة واللقطات إلى سيناريو فيديو Recap.'),
    ],
    'fashion_beauty': [
      AurenTalentSpecializedCapability(id:'fashion_style_lab',name:'Style Lab',prompt:'طوّر أسلوبي في الموضة أو الجمال من الأعمال والصور التي أقدمها مع الحفاظ على هويتي.'),
      AurenTalentSpecializedCapability(id:'lookbook',name:'Lookbook Builder',prompt:'حوّل أعمالي وإطلالاتي إلى Lookbook منظم يوضح الأسلوب والتنوع.'),
      AurenTalentSpecializedCapability(id:'fashion_portfolio',name:'Fashion Portfolio',prompt:'أنشئ Portfolio للموضة أو الجمال يبرز أفضل الأعمال والأدوار والهوية البصرية.'),
      AurenTalentSpecializedCapability(id:'beauty_content',name:'Beauty Content Lab',prompt:'أنشئ أفكار محتوى تعليمية أو إبداعية في الجمال والموضة مناسبة لهويتي.'),
      AurenTalentSpecializedCapability(id:'style_challenge',name:'Style Challenge',prompt:'أنشئ تحديًا إبداعيًا يطور مهارة محددة في الموضة أو الجمال وينتج أعمالًا قابلة للعرض.'),
      AurenTalentSpecializedCapability(id:'fashion_showcase',name:'Style Showcase',prompt:'حوّل أفضل أعمالي إلى Showcase قصير يوضح أسلوبي وتميزي.'),
      AurenTalentSpecializedCapability(id:'fashion_lookbook_visual',name:'Lookbook Visual Studio',prompt:'حوّل الإطلالات إلى تصور Lookbook بصري متناسق.'),
      AurenTalentSpecializedCapability(id:'fashion_video',name:'Fashion Video Studio',prompt:'حوّل الصور والإطلالات إلى تصور فيديو Fashion قصير بحركة وانتقالات.'),
      AurenTalentSpecializedCapability(id:'fashion_cover',name:'Campaign Image Studio',prompt:'أنشئ مفهوم صورة حملة أو غلاف إبداعي لهوية الموهبة.'),
      AurenTalentSpecializedCapability(id:'fashion_media_pack',name:'Fashion Media Pack',prompt:'جهز صورًا وفيديو ومواد عرض متكاملة لملف Talent.'),
    ],
    'food': [
      AurenTalentSpecializedCapability(id:'recipe_lab',name:'Recipe Lab',prompt:'طوّر وصفتي أو فكرتي إلى وصفة واضحة مع مكونات وخطوات وبدائل مناسبة، دون افتراض معلومات غير معروفة.'),
      AurenTalentSpecializedCapability(id:'chef_profile',name:'Chef Profile',prompt:'أنشئ ملف موهبة للطهي يوضح التخصص والوصفات والأعمال والإنجازات التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'food_portfolio',name:'Food Portfolio',prompt:'رتب وصفاتي وأعمالي وصور أطباقي في Food Portfolio جذاب وقابل للمشاركة.'),
      AurenTalentSpecializedCapability(id:'food_story',name:'Food Story',prompt:'حوّل وصفة أو طبقًا إلى قصة محتوى قصيرة توضّح الفكرة والمكونات وطريقة التقديم.'),
      AurenTalentSpecializedCapability(id:'cooking_challenge',name:'Cooking Challenge',prompt:'أنشئ تحديًا في الطبخ يطور مهارة محددة وينتج طبقًا جديدًا قابلًا للعرض.'),
      AurenTalentSpecializedCapability(id:'menu_creative',name:'Menu Creative Lab',prompt:'ساعدني في بناء فكرة قائمة أطباق إبداعية متماسكة حول نوع أو موضوع أختاره.'),
      AurenTalentSpecializedCapability(id:'food_image_studio',name:'Food Visual Studio',prompt:'حوّل الطبق أو الوصفة إلى تصور تصوير بصري جذاب مع التكوين والإضاءة.'),
      AurenTalentSpecializedCapability(id:'food_video',name:'Cooking Video Studio',prompt:'حوّل الوصفة إلى Storyboard لفيديو طبخ خطوة بخطوة.'),
      AurenTalentSpecializedCapability(id:'food_reel',name:'Food Reel Studio',prompt:'أنشئ فكرة Reel قصير للطبق مع Hook ومشاهد وتوقيت.'),
      AurenTalentSpecializedCapability(id:'food_media_pack',name:'Chef Media Pack',prompt:'جهز صور الغلاف والفيديو والوصف ومواد عرض للطباخ أو الموهبة.'),
    ],
    'languages': [
      AurenTalentSpecializedCapability(id:'speaking_coach',name:'Speaking Coach',prompt:'أنشئ لي خطة لتحسين التحدث والوضوح والثقة في اللغة التي أحددها مع تمارين قابلة للمتابعة.'),
      AurenTalentSpecializedCapability(id:'pronunciation_lab',name:'Pronunciation Lab',prompt:'ساعدني في تدريب النطق من الكلمات أو التسجيل الذي أقدمه، وميّز بين الملاحظة والقياس الفعلي.'),
      AurenTalentSpecializedCapability(id:'writing_language',name:'Language Writing Lab',prompt:'راجع كتابتي باللغة التي أحددها وحسن القواعد والوضوح مع الحفاظ على المعنى والأسلوب.'),
      AurenTalentSpecializedCapability(id:'language_challenge',name:'Language Challenge',prompt:'أنشئ تحديًا يوميًا أو أسبوعيًا يطور مهارة محددة في اللغة مع طريقة قياس بسيطة.'),
      AurenTalentSpecializedCapability(id:'communication_portfolio',name:'Communication Portfolio',prompt:'أنشئ ملفًا يوضح اللغات ومستوياتها وأعمال الترجمة أو الكتابة أو التحدث التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'presentation_coach',name:'Presentation Coach',prompt:'جهزني لتقديم عرض أو حديث عام عبر هيكل ورسالة وتمارين وأسئلة متوقعة.'),
      AurenTalentSpecializedCapability(id:'language_video',name:'Language Video Studio',prompt:'حوّل درسًا أو مهارة لغوية إلى فيديو تعليمي قصير بمشاهد ونصوص.'),
      AurenTalentSpecializedCapability(id:'language_visual',name:'Language Visual Studio',prompt:'أنشئ بطاقات وصورًا بصرية تساعد في تعلم الكلمات والنطق.'),
      AurenTalentSpecializedCapability(id:'language_presentation',name:'Presentation Video',prompt:'حوّل عرضًا لغويًا إلى تصور فيديو تدريبي واضح.'),
      AurenTalentSpecializedCapability(id:'language_creator_pack',name:'Language Creator Pack',prompt:'جهز صورًا ومقاطع قصيرة ووصفًا لمحتوى اللغة والموهبة.'),
    ],
    'leadership_impact': [
      AurenTalentSpecializedCapability(id:'leadership_lab',name:'Leadership Lab',prompt:'حلل هدفي القيادي وساعدني في تطوير مهارات التواصل واتخاذ القرار وبناء الفريق.'),
      AurenTalentSpecializedCapability(id:'impact_project',name:'Impact Project Lab',prompt:'حوّل فكرة أثر اجتماعي إلى مشروع بمشكلة وأهداف ومهام ومؤشرات أثر قابلة للمتابعة.'),
      AurenTalentSpecializedCapability(id:'impact_portfolio',name:'Impact Portfolio',prompt:'أنشئ Impact Portfolio من المشاريع والنتائج والأدوار والأدلة التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'leadership_challenge',name:'Leadership Challenge',prompt:'أنشئ لي تحديًا عمليًا يطور مهارة قيادية محددة خلال فترة أختارها.'),
      AurenTalentSpecializedCapability(id:'community_story',name:'Impact Story',prompt:'حوّل مشروع أو إنجاز اجتماعي إلى قصة أثر واضحة تبرز المشكلة والفعل والنتيجة والدليل.'),
      AurenTalentSpecializedCapability(id:'team_builder',name:'Team Builder',prompt:'حدد المهارات المكملة التي أحتاجها لبناء فريق لمشروع أثر اجتماعي مع توضيح أدوار كل نوع من المواهب.'),
      AurenTalentSpecializedCapability(id:'impact_visual',name:'Impact Visual Studio',prompt:'حوّل مشروع الأثر إلى تصور بصري يوضح المشكلة والفعل والنتيجة.'),
      AurenTalentSpecializedCapability(id:'impact_video',name:'Impact Story Video',prompt:'أنشئ Storyboard لفيديو قصة أثر يبرز الدليل والنتيجة.'),
      AurenTalentSpecializedCapability(id:'impact_poster',name:'Impact Campaign Poster',prompt:'أنشئ تصور بوستر لحملة أو مشروع اجتماعي.'),
      AurenTalentSpecializedCapability(id:'impact_media_pack',name:'Impact Media Pack',prompt:'جهز صورًا وفيديو ووصفًا مختصرًا لعرض مشروع الأثر.'),
    ],
    'other': [
      AurenTalentSpecializedCapability(id:'other_skill_lab',name:'Skill Lab',prompt:'ساعدني في تطوير موهبتي المتخصصة عبر تقييم ما أقدمه وبناء تمارين ومهام مناسبة لمستواي.'),
      AurenTalentSpecializedCapability(id:'other_project_lab',name:'Project Lab',prompt:'حوّل مهارتي إلى مشروع عملي يمكنني تنفيذه وعرضه كدليل على الموهبة.'),
      AurenTalentSpecializedCapability(id:'other_portfolio',name:'Portfolio Builder',prompt:'أنشئ Portfolio لموهبتي من الأعمال والإنجازات والأدلة التي أقدمها.'),
      AurenTalentSpecializedCapability(id:'other_challenge',name:'Talent Challenge',prompt:'أنشئ تحديًا عمليًا يطور مهارتي ويخرج منه عمل جديد قابل للعرض.'),
      AurenTalentSpecializedCapability(id:'other_showcase',name:'Showcase Builder',prompt:'حوّل أفضل أعمالي إلى Showcase مختصر يوضح موهبتي وتميزي.'),
      AurenTalentSpecializedCapability(id:'other_growth',name:'Growth Roadmap',prompt:'أنشئ خارطة طريق لتطوير موهبتي حسب مستواي الحالي وهدفي ووقتي.'),
      AurenTalentSpecializedCapability(id:'other_visual_creator',name:'Talent Visual Studio',prompt:'حوّل موهبتي إلى تصور بصري يعرض المهارة والعمل وأفضل الأدلة.'),
      AurenTalentSpecializedCapability(id:'other_video_creator',name:'Talent Video Studio',prompt:'حوّل مهارتي إلى فيديو تعريفي أو Showcase منظم.'),
      AurenTalentSpecializedCapability(id:'other_project_media',name:'Project Media Studio',prompt:'أنشئ صورًا ومشاهد وفيديو لعرض المشروع الذي أبنيه.'),
      AurenTalentSpecializedCapability(id:'other_showcase_pack',name:'Talent Media Pack',prompt:'جهز حزمة عرض تشمل صورة غلاف وفيديو ووصف وأفضل الأدلة.'),
    ],
  };
}
