import 'package:flutter/material.dart';
import '../../../services/education/inclusive_learning_service.dart';
import '../../../services/education/lesson_to_game_service.dart';
import '../../../services/education/adaptive_learning_service.dart';
import '../../../services/education/adaptive_game_progress_service.dart';
class LessonGamesScreen extends StatefulWidget{ final UniversalLesson lesson; final String? uid; const LessonGamesScreen({super.key,required this.lesson,this.uid}); @override State<LessonGamesScreen> createState()=>_LessonGamesScreenState(); }
class _LessonGamesScreenState extends State<LessonGamesScreen>{
double mastery=.5; int gameIndex=0,questionIndex=0; String? selected; final spelling=TextEditingController();
@override void dispose(){spelling.dispose();super.dispose();}
@override Widget build(BuildContext context){ final games=const LessonToGameEngine().gamesFor(widget.lesson,mastery:mastery); final game=games[gameIndex%games.length]; final q=game.questions[questionIndex%game.questions.length]; return Scaffold(appBar:AppBar(title:Text(game.title)),body:ListView(padding:const EdgeInsets.all(16),children:[Text(widget.lesson.title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),LinearProgressIndicator(value:mastery),Text('الإتقان: '+(mastery*100).round().toString()+'% • المستوى: '+game.difficulty.toString()),const SizedBox(height:18),_game(game,q)]));}
Widget _game(LessonGame g,LessonGameQuestion q){switch(g.type){case LessonGameType.flashcards:return _box(g,q,'flash');case LessonGameType.matching:return _box(g,q,'match');case LessonGameType.quiz:return _box(g,q,'quiz');case LessonGameType.spelling:return _box(g,q,'spell');case LessonGameType.speedRound:return _box(g,q,'speed');case LessonGameType.dailyChallenge:return _box(g,q,'daily');}}
Widget _box(LessonGame g,LessonGameQuestion q,String mode){return Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text(q.prompt,style:Theme.of(context).textTheme.titleLarge),if(mode=='spell')TextField(controller:spelling,decoration:const InputDecoration(labelText:'إجابتك')),if(mode=='match'||mode=='quiz')...q.options.map((o)=>RadioListTile<String>(value:o,groupValue:selected,title:Text(o),onChanged:(v)=>setState(()=>selected=v))),const SizedBox(height:12),ElevatedButton(onPressed:()=>_submit(g,q,mode),child:Text(mode=='daily'?'إكمال التحدي':'تحقق')),if(mode=='flash'||mode=='speed')TextButton(onPressed:()=>_submit(g,q,mode),child:const Text('أحتاج مراجعة'))])));}
Future<void> _submit(LessonGame g,LessonGameQuestion q,String mode) async{bool ok=true;if(mode=='match'||mode=='quiz')ok=selected==q.answer;if(mode=='spell')ok=spelling.text.trim().toLowerCase()==q.answer.trim().toLowerCase();final next=AdaptiveLearningService().nextMastery(mastery:mastery,correct:ok,attempts:1);if(widget.uid!=null)await AdaptiveGameProgressService().recordAnswer(widget.uid!,lessonId:widget.lesson.id,game:g,correct:ok,attempts:1);if(!mounted)return;setState((){mastery=next;questionIndex++;selected=null;spelling.clear();if(questionIndex>=g.questions.length){questionIndex=0;gameIndex++;}});ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'إجابة صحيحة + تقدم':'مراجعة مطلوبة')));}
}