import 'package:cloud_firestore/cloud_firestore.dart';
import '../goals/goal_repository.dart';
import '../memory/memory_repository.dart';
import '../business/business_repository.dart';
class AurenOpportunityChainStep{final String id,title,description;final bool completed;const AurenOpportunityChainStep({required this.id,required this.title,required this.description,required this.completed});Map<String,dynamic> toMap()=>{'id':id,'title':title,'description':description,'completed':completed};factory AurenOpportunityChainStep.fromMap(Map<String,dynamic> m)=>AurenOpportunityChainStep(id:m['id']?.toString()??'',title:m['title']?.toString()??'',description:m['description']?.toString()??'',completed:m['completed']==true);}
class AurenOpportunityChain{final String goalTitle,opportunityTitle;final List<AurenOpportunityChainStep> steps;const AurenOpportunityChain({required this.goalTitle,required this.opportunityTitle,required this.steps});}
class AurenOpportunityChainService{final FirebaseFirestore _db;final GoalRepository _goals;final MemoryRepository _memory;final BusinessRepository _business;AurenOpportunityChainService({FirebaseFirestore? firestore}):_db=firestore??FirebaseFirestore.instance,_goals=GoalRepository(firestore:firestore),_memory=MemoryRepository(firestore:firestore),_business=BusinessRepository(firestore:firestore);
Future<AurenOpportunityChain> build(String uid)async{final goals=await _goals.watch(uid).first;final memories=await _memory.watch(uid).first;final businesses=await _business.watchPublic().first;final active=goals.where((g)=>g.status=='active').toList()..sort((a,b)=>a.progress.compareTo(b.progress));final goal=active.isEmpty?null:active.first;final terms=<String>{};if(goal!=null){terms.addAll(_tokens(goal.title));terms.addAll(_tokens(goal.description??''));}for(final m in memories.where((m)=>m.enabled).take(20)){terms.addAll(_tokens(m.key+' '+m.value));}for(final b in businesses.where((b)=>b.ownerId==uid)){terms.addAll(_tokens(b.name+' '+b.category+' '+b.description));}var best=0;var opportunity='ابحث عن فرصة مرتبطة بسياقك';for(final b in businesses.where((b)=>b.ownerId!=uid&&b.visibility=='public')){final t=(b.name+' '+b.description+' '+b.category+' '+b.businessType+' '+b.city+' '+b.country).toLowerCase();final hits=terms.where((x)=>x.length>2&&t.contains(x)).length;if(hits>best){best=hits;opportunity=b.name;}}final title=goal?.title??'هدف جديد';final base=[AurenOpportunityChainStep(id:'chain_1',title:'حدّد الفرصة',description:'اربط الهدف بإشارة فرصة واضحة.',completed:false),AurenOpportunityChainStep(id:'chain_2',title:'تحقق من الملاءمة',description:'راجع المتطلبات والفائدة والمخاطر.',completed:false),AurenOpportunityChainStep(id:'chain_3',title:'جهّز العرض',description:'حوّل مهاراتك أو منتجك أو خدمتك إلى عرض مناسب.',completed:false),AurenOpportunityChainStep(id:'chain_4',title:'تواصل بإذن',description:'جهّز التواصل؛ لا إرسال تلقائي.',completed:false),AurenOpportunityChainStep(id:'chain_5',title:'حوّلها إلى نتيجة',description:'تابع الرد والنتيجة واربطها بهدفك.',completed:false)];final ref=_db.collection('users').doc(uid).collection('opportunity_chain').doc('current');final old=await ref.get();final raw=(old.data()?['steps'] as List?)??[];final oldSteps=raw.map((x)=>AurenOpportunityChainStep.fromMap(Map<String,dynamic>.from(x as Map))).toList();final steps=base.map((s){final m=oldSteps.where((x)=>x.id==s.id);return m.isEmpty?s:AurenOpportunityChainStep(id:s.id,title:s.title,description:s.description,completed:m.first.completed);}).toList();await ref.set({'goalTitle':title,'opportunityTitle':opportunity,'steps':steps.map((s)=>s.toMap()).toList(),'updatedAt':FieldValue.serverTimestamp()});return AurenOpportunityChain(goalTitle:title,opportunityTitle:opportunity,steps:steps);}
Future<void> toggle(String uid,String id,bool value)async{final ref=_db.collection('users').doc(uid).collection('opportunity_chain').doc('current');final snap=await ref.get();final data=snap.data();if(data==null)return;final steps=((data['steps'] as List?)??[]).map((x)=>Map<String,dynamic>.from(x as Map)).toList();for(final s in steps){if(s['id']==id)s['completed']=value;}await ref.update({'steps':steps,'updatedAt':FieldValue.serverTimestamp()});}Set<String> _tokens(String x)=>x.toLowerCase().split(RegExp(r'[^\p{L}\p{N}]+',unicode:true)).where((x)=>x.length>2).toSet();}
