import 'package:cloud_firestore/cloud_firestore.dart';
class MarketplaceCommerceRepository {
  final FirebaseFirestore db;
  MarketplaceCommerceRepository({FirebaseFirestore? firestore}):db=firestore??FirebaseFirestore.instance;
  CollectionReference<Map<String,dynamic>> get products=>db.collection('products');
  CollectionReference<Map<String,dynamic>> get orders=>db.collection('marketplace_orders');
  Future<String> createOrder({required String buyerId,required String productId,required String sellerId,required int quantity,required int unitPriceMinor,required String currency,required String paymentMethod,String? productName,String? productImageUrl}) async {\n    if(!{'cash_on_delivery','pending_gateway'}.contains(paymentMethod)) throw ArgumentError('طريقة دفع غير صالحة');\n    if(quantity<1||quantity>1000) throw ArgumentError('كمية غير صالحة');
    final ref=orders.doc();
    await ref.set({'buyerId':buyerId,'sellerId':sellerId,'productId':productId,'quantity':quantity,'unitPriceMinor':unitPriceMinor,'totalMinor':unitPriceMinor*quantity,'currency':currency,'paymentMethod':paymentMethod,'productName':productName ?? '','productImageUrl':productImageUrl ?? '','status':'pending','createdAt':FieldValue.serverTimestamp()});
    return ref.id;
  }
  Stream<List<Map<String,dynamic>>> watchBuyerOrders(String uid)=>orders.where('buyerId',isEqualTo:uid).limit(100).snapshots().map((s)=>s.docs.map((d)=>{'id':d.id,...d.data()}).toList());
  Stream<List<Map<String,dynamic>>> watchSellerOrders(String uid)=>orders.where('sellerId',isEqualTo:uid).limit(100).snapshots().map((s)=>s.docs.map((d)=>{'id':d.id,...d.data()}).toList());
  Future<Map<String,int>> sellerFinancialSummary(String uid) async {\n    final snap=await orders.where('sellerId',isEqualTo:uid).limit(500).get();\n    var gross=0; var commission=0; var count=0;\n    for(final d in snap.docs){final x=d.data();if(x['status']=='cancelled') continue; final total=(x['totalMinor'] as num?)?.toInt()??0; gross+=total; commission+=(total*5/100).round(); count++;}\n    return {'orders':count,'grossMinor':gross,'commissionMinor':commission,'netMinor':gross-commission};\n  }\n  Future<void> updateOrderStatus(String id,String status) async {\n    const allowed={'pending','confirmed','processing','shipped','delivered','cancelled'};\n    if(!allowed.contains(status)) throw ArgumentError('حالة طلب غير صالحة');\n    await orders.doc(id).update({'status':status,'updatedAt':FieldValue.serverTimestamp()});\n  }\n  Future<void> updateCartQuantity({required String uid,required String productId,required int quantity}) async {\n    if(quantity<1){await removeFromCart(uid,productId);return;}\n    if(quantity>100) throw ArgumentError('الكمية القصوى 100');\n    await db.collection('users').doc(uid).collection('cart').doc(productId).update({'quantity':quantity});\n  }
  Future<void> addToCartWithSnapshot({required String uid,required String productId,required int quantity}) async { final p=await products.doc(productId).get(); if(!p.exists||p.data()==null) throw StateError('المنتج غير موجود'); final d=p.data()!; await db.collection('users').doc(uid).collection('cart').doc(productId).set({'productId':productId,'name':d['name'],'sellerId':d['ownerId'],'unitPriceMinor':d['priceMinor'],'currency':d['currency'],'quantity':quantity.clamp(1,100),'addedAt':FieldValue.serverTimestamp()}); }
  Future<String> checkoutCart({required String uid,required String paymentMethod}) async {\n    final snap=await db.collection('users').doc(uid).collection('cart').get();\n    if(snap.docs.isEmpty) throw StateError('السلة فارغة');\n    String firstOrder='';\n    final validated=<Map<String,dynamic>>[];\n    for(final cart in snap.docs){\n        final x=cart.data();\n        final productId=x['productId']?.toString() ?? cart.id;\n        final quantity=(x['quantity'] as num?)?.toInt() ?? 1;\n        final product=await products.doc(productId).get();\n        if(!product.exists||product.data()==null) throw StateError('المنتج لم يعد متاحاً: $productId');\n        final d=product.data()!;\n        if((d['status']?.toString() ?? 'active')!='active') throw StateError('المنتج غير متاح حالياً: ${d['name'] ?? productId}');\n        final sellerId=d['ownerId']?.toString() ?? '';\n        final price=(d['priceMinor'] as num?)?.toInt() ?? 0;\n        final currency=d['currency']?.toString() ?? 'USD';\n        if(sellerId.isEmpty) throw StateError('المنتج لا يملك بائعاً صالحاً: $productId');\n        if(quantity<1||quantity>1000) throw StateError('كمية غير صالحة: $productId');\n        validated.add({'cart':cart,'productId':productId,'sellerId':sellerId,'quantity':quantity,'price':price,'currency':currency,'name':d['name']?.toString() ?? '','imageUrl':d['imageUrl']?.toString() ?? ''});\n    }\n    for(final v in validated){\n      final id=await createOrder(buyerId:uid,productId:v['productId'],sellerId:v['sellerId'],quantity:v['quantity'],unitPriceMinor:v['price'],currency:v['currency'],paymentMethod:paymentMethod,productName:v['name'],productImageUrl:v['imageUrl']);\n      firstOrder=firstOrder.isEmpty?id:firstOrder;\n    }\n    for(final cart in snap.docs) await cart.reference.delete();\n    return firstOrder;\n  }
  Stream<List<Map<String,dynamic>>> watchCart(String uid)=>db.collection('users').doc(uid).collection('cart').orderBy('addedAt',descending:true).snapshots().map((s)=>s.docs.map((d)=>{'id':d.id,...d.data()}).toList());
  Future<void> addToCart({required String uid,required String productId,required int quantity})=>addToCartWithSnapshot(uid:uid,productId:productId,quantity:quantity);
  Future<void> removeFromCart(String uid,String productId)=>db.collection('users').doc(uid).collection('cart').doc(productId).delete();
  Future<void> saveOffer({required String productId,required String ownerId,required String title,required int percent})=>products.doc(productId).collection('offers').doc('active').set({'productId':productId,'ownerId':ownerId,'title':title,'percent':percent,'active':true,'createdAt':FieldValue.serverTimestamp()});
  Stream<Map<String,dynamic>?> watchOffer(String productId)=>products.doc(productId).collection('offers').doc('active').snapshots().map((d)=>d.exists?d.data():null);
  Future<void> review({required String productId,required String userId,required int rating,required String text})=>products.doc(productId).collection('reviews').doc(userId).set({'productId':productId,'userId':userId,'rating':rating,'text':text,'createdAt':FieldValue.serverTimestamp()});
  Stream<List<Map<String,dynamic>>> watchReviews(String productId)=>products.doc(productId).collection('reviews').orderBy('createdAt',descending:true).limit(50).snapshots().map((s)=>s.docs.map((d)=>d.data()).toList());
  Stream<List<Map<String,dynamic>>> watchAnalytics(String productId)=>products.doc(productId).collection('events').orderBy('createdAt',descending:true).limit(100).snapshots().map((s)=>s.docs.map((d)=>d.data()).toList());
}
