import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../../../services/agriculture/irrigation_intelligence_service.dart';

class IrrigationIntelligenceScreen extends StatefulWidget{const IrrigationIntelligenceScreen({super.key});@override State<IrrigationIntelligenceScreen> createState()=>_IrrigationIntelligenceScreenState();}
class _IrrigationIntelligenceScreenState extends State<IrrigationIntelligenceScreen>{
 final s=IrrigationIntelligenceService();final crop=TextEditingController();final field=TextEditingController();final area=TextEditingController(text:'1');final soil=TextEditingController(text:'0');final need=TextEditingController(text:'30');final rain=TextEditingController(text:'0');final eff=TextEditingController(text:'80');
 @override void dispose(){for(final c in[crop,field,area,soil,need,rain,eff])c.dispose();super.dispose();}
 Widget input(TextEditingController c,String l)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));
 @override Widget build(BuildContext context){final uid=FirebaseAuth.instance.currentUser?.uid;return Scaffold(appBar:AppBar(title:const Text('AUREN Irrigation Intelligence')),body:ListView(padding:const EdgeInsets.all(16),children:[const Text('إدارة المياه والري الذكي',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('تقدير احتياج الري الأسبوعي اعتماداً على احتياج المحصول والمطر ورطوبة التربة وكفاءة النظام. القيم تقديرية ويجب ضبطها ببيانات الحقل المحلية.'),const SizedBox(height:16),TextField(controller:crop,decoration:const InputDecoration(labelText:'المحصول',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:field,decoration:const InputDecoration(labelText:'الحقل / المزرعة',border:OutlineInputBorder())),const SizedBox(height:10),input(area,'المساحة (هكتار)'),input(soil,'ماء متاح في التربة (مم)'),input(need,'احتياج المحصول الأسبوعي (مم)'),input(rain,'مطر متوقع للأسبوع (مم)'),input(eff,'كفاءة الري (%)'),FilledButton.icon(onPressed:uid==null?null:()=>create(uid),icon:const Icon(Icons.water_drop_outlined),label:const Text('احسب خطة الري')),if(uid!=null)...[const SizedBox(height:20),const Text('خطط الري المحفوظة',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),StreamBuilder<List<IrrigationPlan>>(stream:s.watch(uid),builder:(c,x){final rows=x.data??const<IrrigationPlan>[];if(rows.isEmpty)return const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('لا توجد خطط محفوظة.')));return Column(children:rows.map(card).toList());})]]) ;}
 Future<void> create(String uid)async{final p=s.calculate(crop:crop.text,field:field.text,areaHa:double.tryParse(area.text)??0,soilWaterMm:double.tryParse(soil.text)??0,weeklyCropNeedMm:double.tryParse(need.text)??0,rainfallMm:double.tryParse(rain.text)??0,efficiencyPercent:double.tryParse(eff.text)??0);if(p.crop.isEmpty||p.field.isEmpty)return;await s.save(uid,p);if(!mounted)return;showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('خطة الري جاهزة'),content:Text('الري الإجمالي: '+p.irrigationMm.toStringAsFixed(1)+' مم/أسبوع\nالماء التقريبي: '+p.weeklyWaterM3.toStringAsFixed(1)+' م³/أسبوع\n'+p.checks.join('\n')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('تم'))]));}
 Widget card(IrrigationPlan p)=>Card(child:ListTile(title:Text(p.crop+' • '+p.field,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('ري: '+p.irrigationMm.toStringAsFixed(1)+' مم/أسبوع • '+p.weeklyWaterM3.toStringAsFixed(1)+' م³'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:(){final uid=FirebaseAuth.instance.currentUser?.uid;if(uid!=null)s.delete(uid,p.id);}));
}